class ls_ammo_40mm_G77_HEAB: G_40mm_HE {
    ace_frag_enabled = 0;
    ace_frag_metal = 0;
    ace_frag_charge = 0;
    ace_frag_gurney_c = 0;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_tiny_HD"};
    ace_frag_skip = 1;
    ace_frag_force = 0;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 0;
    indirectHitRange = 0;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 7;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    submunitionAmmo = "ls_ammo_40mm_IM973B_HEAB_submunition";
    submunitionConeType[] = {"randomupcone", 1};
    submunitionConeAngle = 0;
    deleteParentWhenTriggered = 1;
    triggerOnImpact = 1;
    submunitionInitSpeed = 50;
    submunitionParentSpeedCoef = 0.001;
    submunitionInitialOffset[] = {0, 0,-0.2};
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss", 1.1622777, 1.4, 1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss", 1.1622777, 1.4, 1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss", 1.1622777, 1.4, 1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss", 1.1622777, 1.4, 1500};
    multiSoundHit[] = {"soundHit1", 0.25, "soundHit2", 0.25, "soundHit3", 0.25, "soundHit4", 0.25};
    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.5964;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.4;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};

class ls_ammo_40mm_IM41_HE: G_40mm_HE {
    ace_frag_enabled = 1;
    ace_frag_metal = 198;
    ace_frag_charge = 32;
    ace_frag_gurney_c = 2700;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_tiny_HD"};
    ace_frag_skip = 0;
    ace_frag_force = 1;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 15;
    indirectHitRange = 6;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 7;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss",1.1622777,1.4,1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss",1.1622777,1.4,1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss",1.1622777,1.4,1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss",1.1622777,1.4,1500};
    multiSoundHit[] = {"soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25};
    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.5964;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.4;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};
AMMO_NOPARENT_NOEFFECTS(40mm_IM41_HE,ls_ammo_40mm_IM41_HE);
DEPRECATED(ls_40mm_he_blue,ls_ammo_40mm_IM41_HE_blue);
DEPRECATED(ls_40mm_he_red,ls_ammo_40mm_IM41_HE_red);
DEPRECATED(ls_40mm_he_green,ls_ammo_40mm_IM41_HE_green);
DEPRECATED(ls_40mm_he_yellow,ls_ammo_40mm_IM41_HE_yellow);

class ls_ammo_40mm_IM92F_HEF: G_40mm_HE {
    ace_frag_enabled = 1;
    ace_frag_metal = 2110;
    ace_frag_charge = 250;
    ace_frag_gurney_c = 2440;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_medium_HD"};
    ace_frag_skip = 0;
    ace_frag_force = 1;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 5;
    indirectHitRange = 16;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 10;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss",1.1622777,1.4,1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss",1.1622777,1.4,1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss",1.1622777,1.4,1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss",1.1622777,1.4,1500};
    multiSoundHit[] = {"soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25};
    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.5964;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.4;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};

class ls_ammo_40mm_IM304D_HEDP: G_40mm_HE {
    ace_frag_enabled = 1;
    ace_frag_metal = 185;
    ace_frag_charge = 45;
    ace_frag_gurney_c = 2700;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_tiny_HD"};
    ace_frag_skip = 0;
    ace_frag_force = 1;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    hit = 50;
    indirectHit = 10;
    indirectHitRange = 7;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 7;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    submunitionAmmo = "ls_ammo_40mm_IM304D_submunition";
    submunitionDirectionType = "SubmunitionModelDirection";
    submunitionInitSpeed = 1000;
    deleteParentWhenTriggered = 0;
    triggerOnImpact = 1;
    submunitionParentSpeedCoef = 1;
    submunitionInitialOffset[] = {0, 0, -0.2};
    soundHit1[] = {"\A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01", 1.1622777, 1.4, 1500};
    soundHit2[] = {"\A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02", 1.1622777, 1.4, 1500};
    soundHit3[] = {"\A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03", 1.1622777, 1.4, 1500};
    soundHit4[] = {"\A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04", 1.1622777, 1.4, 1500};
    multiSoundHit[] = {
        "soundHit1", 0.25,
        "soundHit2", 0.25,
        "soundHit3", 0.25,
        "soundHit4", 0.25
    };

    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.596397;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.40000001;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};
class ls_ammo_40mm_IM304D_submunition: ammo_Penetrator_Base {
    hit = 185;
    warheadName = "HEAT";
    caliber = 5.07;
};

class ls_ammo_40mm_IM334K_HEAT: G_40mm_HE {
    ace_frag_enabled = 1;
    ace_frag_metal = 212;
    ace_frag_charge = 38;
    ace_frag_gurney_c = 2830;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_tiny_HD"};
    ace_frag_skip = 0;
    ace_frag_force = 1;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 10;
    indirectHitRange = 5;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 10;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    submunitionAmmo = "ls_IM334K_Penetrator";
    submunitionDirectionType = "SubmunitionModelDirection";
    submunitionInitSpeed = 1000;
    triggerOnImpact = 1;
    submunitionParentSpeedCoef = 1;
    deleteParentWhenTriggered = 0;
    submunitionInitialOffset[] = {0,0,-0.2};
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss",1.1622777,1.4,1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss",1.1622777,1.4,1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss",1.1622777,1.4,1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss",1.1622777,1.4,1500};
    multiSoundHit[] = {"soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25};
    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.5964;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.4;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};

class ls_ammo_40mm_IM973B_HEAB: G_40mm_HE {
    ace_frag_enabled = 0;
    ace_frag_metal = 0;
    ace_frag_charge = 0;
    ace_frag_gurney_c = 0;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_tiny_HD"};
    ace_frag_skip = 1;
    ace_frag_force = 0;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 0;
    indirectHitRange = 0;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 7;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    submunitionAmmo = "ls_ammo_40mm_IM973B_HEAB_submunition";
    submunitionConeType[] = {"randomupcone",1};
    submunitionConeAngle = 0;
    deleteParentWhenTriggered = 1;
    triggerOnImpact = 1;
    submunitionInitSpeed = 50;
    submunitionParentSpeedCoef = 0.001;
    submunitionInitialOffset[] = {0,0,-0.2};
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss",1.1622777,1.4,1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss",1.1622777,1.4,1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss",1.1622777,1.4,1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss",1.1622777,1.4,1500};
    multiSoundHit[] = {"soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25};
    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.5964;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.4;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};
class ls_ammo_40mm_IM973B_HEAB_submunition: G_40mm_HE {
    ace_frag_enabled = 1;
    ace_frag_metal = 200;
    ace_frag_charge = 32;
    ace_frag_gurney_c = 2800;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_tiny_HD"};
    ace_frag_skip = 0;
    ace_frag_force = 1;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 10;
    indirectHitRange = 7.5;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 0;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    explosionTime = 0.1;
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss", 1.1622777, 1.4, 1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss", 1.1622777, 1.4, 1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss", 1.1622777, 1.4, 1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss", 1.1622777, 1.4, 1500};
    multiSoundHit[] = {"soundHit1", 0.25, "soundHit2", 0.25, "soundHit3", 0.25, "soundHit4", 0.25};
};

class ls_ammo_40mm_G76_HEF: G_40mm_HE {
    ace_frag_enabled = 1;
    ace_frag_metal = 2110;
    ace_frag_charge = 250;
    ace_frag_gurney_c = 2440;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_medium_HD"};
    ace_frag_skip = 0;
    ace_frag_force = 1;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 5;
    indirectHitRange = 16;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 10;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss", 1.1622777, 1.4, 1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss", 1.1622777, 1.4, 1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss", 1.1622777, 1.4, 1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss", 1.1622777, 1.4, 1500};
    multiSoundHit[] = {"soundHit1", 0.25, "soundHit2", 0.25, "soundHit3", 0.25, "soundHit4", 0.25};
    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.5964;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.4;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};

class ls_ammo_40mm_G75_HE: G_40mm_HE {
    ace_frag_enabled = 1;
    ace_frag_metal = 198;
    ace_frag_charge = 32;
    ace_frag_gurney_c = 2700;
    ace_frag_gurney_k = 3/5;
    ace_frag_classes[] = {"ACE_frag_tiny_HD"};
    ace_frag_skip = 0;
    ace_frag_force = 1;
    explosionSoundEffect = "DefaultExplosion";
    simulation = "shotShell";
    aiAmmoUsageFlags = "64";
    tracerScale = 1.6;
    tracerStartTime = 0.1;
    tracerEndTime = 20;
    brightness = 100000;
    hit = 50;
    indirectHit = 15;
    indirectHitRange = 6;
    warheadName = "HE";
    visibleFire = 1;
    audibleFire = 30;
    visibleFireTime = 3;
    dangerRadiusHit = 60;
    suppressionRadiusHit = 24;
    explosive = 1;
    cost = 25;
    deflecting = 0;
    airFriction = -0.001;
    fuseDistance = 7;
    whistleDist = 16;
    typicalSpeed = 76;
    caliber = 2;
    timeToLive = 15;
    soundHit1[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_01.wss",1.1622777,1.4,1500};
    soundHit2[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_02.wss",1.1622777,1.4,1500};
    soundHit3[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_03.wss",1.1622777,1.4,1500};
    soundHit4[] = {"A3\Sounds_F\arsenal\explosives\Grenades\Explosion_gng_grenades_04.wss",1.1622777,1.4,1500};
    multiSoundHit[] = {"soundHit1",0.25,"soundHit2",0.25,"soundHit3",0.25,"soundHit4",0.25};
    class CamShakeExplode {
        power = 8;
        duration = 1.2;
        frequency = 20;
        distance = 74.5964;
    };
    class CamShakeHit {
        power = 20;
        duration = 0.4;
        frequency = 20;
        distance = 1;
    };
    class CamShakeFire {
        power = 0;
        duration = 0.2;
        frequency = 20;
        distance = 0;
    };
    class CamShakePlayerFire {
        power = 0;
        duration = 0.1;
        frequency = 20;
        distance = 1;
    };
};
