#undef UNITS_LIST
#define UNITS_LIST \
"lsd_gar_phase2_base", \
"lsd_gar_phase2Insulated_base", \
"lsd_gar_bodyGloveLegArmor_base", \
"lsd_gar_bodyGlove_base", \
"lsd_bodyGlove_base", \
"ls_gar_marshalCommander_base", \
"lsd_gar_arc_base", \
"ls_sob_commando_unit", \
"ls_sob_commando_hologram_unit", \
"ls_sob_commando_activeCamo_unit", \
"ls_sob_commando_sl_unit", \
"ls_sob_commando_eod_unit", \
"ls_sob_commando_tech_unit", \
"ls_sob_commando_sniper_unit", \
"ls_gar_phase2Hologram_base", \
"ls_gar_airborne_helmet_GH", \
"ls_gar_arc_helmet_GH", \
"ls_gar_arcHologram_helmet_GH", \
"ls_gar_phase1Arf_helmet_GH", \
"ls_gar_phase1ArfHologram_helmet_GH", \
"ls_gar_phase2Arf_helmet_GH", \
"ls_gar_phase2ArfHologram_helmet_GH", \
"ls_gar_atrtDriver_helmet_GH", \
"ls_gar_atrtDriverHologram_helmet_GH", \
"ls_gar_barc_helmet_GH", \
"ls_gar_barcHologram_helmet_GH", \
"ls_gar_cadet_helmet_GH", \
"ls_sob_commando_helmet_GH", \
"ls_sob_commando_hologram_helmet_GH", \
"ls_sob_crosshair_helmet_GH", \
"ls_gar_desert_helmet_GH", \
"ls_gar_desertHologram_helmet_GH", \
"ls_gar_engineer_helmet_GH", \
"ls_sob_hunter_helmet_GH", \
"ls_sob_fordo_helmet_GH", \
"ls_sob_fordoHologram_helmet_GH", \
"ls_gar_phase1_helmet_GH", \
"ls_gar_phase1Hologram_helmet_GH", \
"ls_gar_phase1Pilot_helmet_GH", \
"ls_gar_phase1Pilot_republic_helmet_GH", \
"ls_gar_phase1Pilot_enforcer_helmet_GH", \
"ls_sob_phase1Pilot_helmet_GH", \
"ls_sob_phase1SpecOp_helmet_GH", \
"ls_gar_phase2_helmet_GH", \
"ls_gar_phase2Insulated_helmet_GH", \
"ls_gar_phase2Hologram_helmet_GH", \
"ls_gar_phase2Pilot_helmet_GH", \
"ls_gar_phase2SpecOp_helmet_GH", \
"ls_gar_rex_helmet_GH", \
"ls_gar_scout_helmet_GH", \
"ls_sob_tech_helmet_GH", \
"ls_sob_wrecker_helmet_GH", \
"ls_gar_arc_backpack", \
"ls_gar_beltBag", \
"ls_gar_beltBag_belt", \
"ls_gar_beltBag_leg", \
"ls_sob_commando_backpack", \
"ls_sob_commando_backpack_activeCamo", \
"ls_sob_commando_eod_backpack", \
"ls_sob_commando_eod_backpack_activeCamo", \
"ls_sob_commando_rto_backpack", \
"ls_sob_commando_rto_backpack_activeCamo", \
"ls_sob_commando_tech_backpack", \
"ls_sob_commando_tech_backpack_activeCamo", \
"ls_gar_hawkbat_backpack", \
"ls_gar_hawkbat_backpack_reserve", \
"ls_gar_hawkbat_parachuteSteerable", \
"ls_gar_hawkbat_parachuteSteerable_reserve", \
"ls_sob_commando_backpack_deltaBoss", \
"ls_sob_commando_backpack_deltaFixer", \
"ls_sob_commando_backpack_deltaScorch", \
"ls_sob_commando_backpack_deltaSev", \
"ls_sob_commando_backpack_gregor", \
"ls_sob_commando_backpack_mpGunner", \
"ls_sob_commando_backpack_mpMarksman", \
"ls_sob_commando_backpack_mpRecon", \
"ls_sob_commando_backpack_mpStealth", \
"ls_sob_commando_backpack_omegaNiner", \
"ls_sob_commando_backpack_omegaDarman", \
"ls_sob_commando_backpack_omega", \
"ls_sob_commando_backpack_yayaxDev", \
"ls_sob_commando_backpack_yayaxYover"

#undef WEAPONS_LIST
#define WEAPONS_LIST \
"ls_gar_arc_helmet", \
"ls_gar_arcHologram_helmet", \
"ls_gar_phase1Arf_helmet", \
"ls_gar_phase1ArfHologram_helmet", \
"ls_gar_phase2Arf_helmet", \
"ls_gar_phase2ArfHologram_helmet", \
"ls_gar_atrtDriver_helmet", \
"ls_gar_atrtDriverHologram_helmet", \
"ls_gar_barc_helmet", \
"ls_gar_barcHologram_helmet", \
"ls_gar_cadet_helmet", \
"ls_sob_commando_helmet", \
"ls_sob_commando_hologram_helmet", \
"ls_sob_commando_helmet_activeCamo", \
"ls_sob_crosshair_helmet", \
"ls_gar_desert_helmet", \
"ls_gar_desertHologram_helmet", \
"ls_gar_engineer_helmet", \
"ls_sob_hunter_helmet", \
"ls_sob_fordo_helmet", \
"ls_sob_fordoHologram_helmet", \
"ls_gar_phase1_helmet", \
"ls_gar_phase1Hologram_helmet", \
"ls_gar_phase1Pilot_helmet", \
"ls_gar_phase1Pilot_republic_helmet", \
"ls_gar_phase1Pilot_enforcer_helmet", \
"ls_sob_phase1SpecOp_helmet", \
"ls_gar_phase2_helmet", \
"ls_gar_phase2Insulated_helmet", \
"ls_gar_phase2Hologram_helmet", \
"ls_gar_phase2Pilot_helmet", \
"ls_sob_phase2SpecOp_helmet", \
"ls_gar_rex_helmet", \
"ls_gar_scout_helmet", \
"ls_sob_tech_helmet", \
"ls_sob_wrecker_helmet", \
"ls_gar_phase2_uniform", \
"ls_gar_phase2Insulated_uniform", \
"lsd_gar_bodyGlove_uniform", \
"lsd_gar_bodyGloveLegArmor_uniform", \
"lsd_bodyglove_uniform", \
"ls_gar_phase2Hologram_uniform", \
"ls_gar_airborne_vest", \
"ls_gar_airborneNCO_vest", \
"ls_gar_airborneCFR_vest", \
"ls_gar_airborneLight_vest", \
"ls_gar_airborneOfficer_vest", \
"lsd_gar_alphaArc_vest_blue", \
"lsd_gar_alphaArc_vest_red", \
"lsd_gar_alphaArc_vest_yellow", \
"ls_gar_arc_vest", \
"ls_gar_arcHologram_vest", \
"ls_gar_arf_vest", \
"ls_gar_assault_vest", \
"ls_gar_clone_vest", \
"ls_gar_holster_vest", \
"ls_gar_engineer_vest", \
"ls_gar_engineerNCO_vest", \
"ls_gar_engineerOfficer_vest", \
"ls_gar_forceRecon_vest", \
"ls_gar_forceReconNCO_vest", \
"ls_gar_forceReconOfficer_vest", \
"ls_gar_forceReconCommander_vest", \
"ls_gar_forceReconLieutenant_vest", \
"ls_gar_grenadier_vest", \
"ls_gar_hazard_vest", \
"ls_gar_heavy_vest", \
"ls_gar_heavyAlt_vest", \
"ls_gar_lanceCaptain_vest", \
"ls_gar_lanceCommander_vest", \
"ls_gar_medic_vest", \
"ls_gar_cfr_vest", \
"ls_gar_kama_vest", \
"ls_gar_kama_rank_vest", \
"ls_gar_kamaAntenna_vest", \
"ls_gar_lieutenant_vest", \
"ls_gar_officer_vest", \
"ls_gar_officer_black_vest", \
"ls_gar_commander_vest", \
"ls_gar_commander_black_vest", \
"ls_gar_commander_rank_vest", \
"ls_gar_rebreather_vest", \
"ls_gar_rebreatherTubes_vest", \
"ls_gar_recon_vest", \
"ls_gar_reconNCO_vest", \
"ls_gar_reconNCO_alternate_vest", \
"ls_gar_reconOfficer_vest", \
"ls_gar_specialist_vest", \
"ls_gar_tacticalOfficer_vest", \
"ls_gar_tacticalCommander_vest"