#define UNITS_LIST \
"ls_static_base", \
"ls_bloodPool_green1", \
"ls_bloodPool_green2", \
"ls_bloodPool_green3", \
"ls_bloodPool_green4", \
"ls_bloodPool_black1", \
"ls_bloodPool_black2", \
"ls_bloodPool_black3", \
"ls_bloodPool_black4", \
"ls_bloodPool_blue1", \
"ls_bloodPool_blue2", \
"ls_bloodPool_blue3", \
"ls_bloodPool_blue4", \
"ls_firstShot_bottle", \
"ls_commandPost_blue_base", \
"ls_commandPost_green_base", \
"ls_commandPost_red_base", \
"ls_commandPost_yellow_base", \
"ls_commandPost_white_base", \
"ls_commandPost_blackSun_blue", \
"ls_commandPost_blackSun_green", \
"ls_commandPost_blackSun_red", \
"ls_commandPost_blackSun_yellow", \
"ls_commandPost_blackSun_white", \
"ls_commandPost_cis_blue", \
"ls_commandPost_cis_green", \
"ls_commandPost_cis_red", \
"ls_commandPost_cis_yellow", \
"ls_commandPost_cis_white", \
"ls_commandPost_zannConsortium_blue", \
"ls_commandPost_zannConsortium_green", \
"ls_commandPost_zannConsortium_red", \
"ls_commandPost_zannConsortium_yellow", \
"ls_commandPost_zannConsortium_white", \
"ls_commandPost_deathwatch_blue", \
"ls_commandPost_deathwatch_green", \
"ls_commandPost_deathwatch_red", \
"ls_commandPost_deathwatch_yellow", \
"ls_commandPost_deathwatch_white", \
"ls_commandPost_imperial_blue", \
"ls_commandPost_imperial_green", \
"ls_commandPost_imperial_red", \
"ls_commandPost_imperial_yellow", \
"ls_commandPost_imperial_white", \
"ls_commandPost_jedi_blue", \
"ls_commandPost_jedi_green", \
"ls_commandPost_jedi_red", \
"ls_commandPost_jedi_yellow", \
"ls_commandPost_jedi_white", \
"ls_commandPost_mandalorian_blue", \
"ls_commandPost_mandalorian_green", \
"ls_commandPost_mandalorian_red", \
"ls_commandPost_mandalorian_yellow", \
"ls_commandPost_mandalorian_white", \
"ls_commandPost_rebel_blue", \
"ls_commandPost_rebel_green", \
"ls_commandPost_rebel_red", \
"ls_commandPost_rebel_yellow", \
"ls_commandPost_rebel_white", \
"ls_commandPost_republic_blue", \
"ls_commandPost_republic_green", \
"ls_commandPost_republic_red", \
"ls_commandPost_republic_yellow", \
"ls_commandPost_republic_white", \
"ls_commandPost_sith_blue", \
"ls_commandPost_sith_green", \
"ls_commandPost_sith_red", \
"ls_commandPost_sith_yellow", \
"ls_commandPost_sith_white",  \
"ls_flag_base", \
"ls_flag_republic", \
"ls_flag_republic_damaged", \
"ls_flag_republicNavy", \
"ls_flag_republicNavy_damaged", \
"ls_flag_cis", \
"ls_flag_cis_damaged", \
"ls_flag_imperial", \
"ls_flag_imperial_damaged", \
"ls_flag_jedi", \
"ls_flag_jedi_damaged", \
"ls_flag_mandalorian", \
"ls_flag_mandalorian_damaged", \
"ls_flag_rebelAlliance", \
"ls_flag_rebelAlliance_damaged", \
"ls_flag_technoUnion", \
"ls_flag_technoUnion_damaged", \
"ls_flag_tradeFederation", \
"ls_flag_tradeFederation_damaged", \
"ls_staticFlag_republic", \
"ls_staticFlag_republic_damaged", \
"ls_staticFlag_republicNavy", \
"ls_staticFlag_republicNavy_damaged", \
"ls_staticFlag_cis", \
"ls_staticFlag_cis_damaged", \
"ls_staticFlag_imperial", \
"ls_staticFlag_imperial_damaged", \
"ls_staticFlag_jedi", \
"ls_staticFlag_jedi_damaged", \
"ls_staticFlag_mandalorian", \
"ls_staticFlag_mandalorian_damaged", \
"ls_staticFlag_rebelAlliance", \
"ls_staticFlag_rebelAlliance_damaged", \
"ls_staticFlag_technoUnion", \
"ls_staticFlag_technoUnion_damaged", \
"ls_staticFlag_tradeFederation", \
"ls_staticFlag_tradeFederation_damaged", \
"ls_staticFlag_republic_vertical", \
"ls_staticFlag_republic_damaged_vertical", \
"ls_staticFlag_republicNavy_vertical", \
"ls_staticFlag_republicNavy_damaged_vertical", \
"ls_staticFlag_cis_vertical", \
"ls_staticFlag_cis_damaged_vertical", \
"ls_staticFlag_imperial_vertical", \
"ls_staticFlag_imperial_damaged_vertical", \
"ls_staticFlag_jedi_vertical", \
"ls_staticFlag_jedi_damaged_vertical", \
"ls_staticFlag_mandalorian_vertical", \
"ls_staticFlag_mandalorian_damaged_vertical", \
"ls_staticFlag_rebelAlliance_vertical", \
"ls_staticFlag_rebelAlliance_damaged_vertical", \
"ls_staticFlag_technoUnion_vertical", \
"ls_staticFlag_technoUnion_damaged_vertical", \
"ls_staticFlag_tradeFederation_vertical", \
"ls_staticFlag_tradeFederation_damaged_vertical", \
"ls_mse6", \
"ls_mse7", \
"ls_radio", \
"ls_reinsertTerminal", \
"ls_standardFlag_republic", \
"ls_supplies_emptyResupply", \
"ls_supplies_dc15aResupply", \
"ls_supplies_dc15sResupply", \
"ls_supplies_z6Resupply", \
"ls_supplies_generalResupply", \
"ls_supplies_rocketResupply", \
"ls_supplies_grenadeResupply", \
"ls_supplies_rpsResupply", \
"ls_supplies_plxResupply", \
"ls_supplies_e60rResupply", \
"ls_supplies_commandoResupply", \
"ls_supplies_republicAssaultResupply", \
"ls_supplies_droidAssaultResupply", \
"ls_supplies_republicSpecOpsResupply", \
"ls_supplies_eodResupply", \
"ls_stimbox", \
"ls_smallComputer", \
"ls_disabledB1", \
"ls_disabledB1_magicDroid", \
"ls_sweeperDroid_green", \
"ls_sweeperDroid_red", \
"ls_sweeperDroid_orange", \
"ls_static_vulture"

#define WEAPONS_LIST ""
