class ls_bullet_flyby_soundSet: bulletFlyBy_SoundSet {
    soundShaders[] = {"ls_bullet_flyby_soundShader"};
};

#include "acpa\CfgSoundSets.hpp"
#include "acpr\CfgSoundSets.hpp"
#include "dc15a\CfgSoundSets.hpp"
#include "dc15b\CfgSoundSets.hpp"
#include "dc15c\CfgSoundSets.hpp"
#include "dc15l\CfgSoundSets.hpp"
#include "dc15s\CfgSoundSets.hpp"
#include "dc15sa\CfgSoundSets.hpp"
#include "dc15x\CfgSoundSets.hpp"
#include "dc17m\CfgSoundSets.hpp"
#include "dc17s\CfgSoundSets.hpp"
#include "dp20\CfgSoundSets.hpp"
#include "dw32s\CfgSoundSets.hpp"
#include "e5\CfgSoundSets.hpp"
#include "e5c\CfgSoundSets.hpp"
#include "e5s\CfgSoundSets.hpp"
#include "e5x\CfgSoundSets.hpp"
#include "e11\CfgSoundSets.hpp"
#include "e60r\CfgSoundSets.hpp"
#include "ls150\CfgSoundSets.hpp"
#include "medBlaster\CfgSoundSets.hpp"
#include "mercenarySniper\CfgSoundSets.hpp"
#include "firepuncher\CfgSoundSets.hpp"
#include "mpl\CfgSoundSets.hpp"
#include "plx1\CfgSoundSets.hpp"
#include "rd4\CfgSoundSets.hpp"
#include "rg4d\CfgSoundSets.hpp"
#include "ugl\CfgSoundSets.hpp"
#include "valken38x\CfgSoundSets.hpp"
#include "westar35c\CfgSoundSets.hpp"
#include "westar35s\CfgSoundSets.hpp"
#include "westar35sa\CfgSoundSets.hpp"
#include "westarM5\CfgSoundSets.hpp"
#include "wristblaster\CfgSoundSets.hpp"
#include "z6\CfgSoundSets.hpp"
#include "zh73\CfgSoundSets.hpp"
