#undef UNITS_LIST
#define UNITS_LIST \
"ls_staticShip_base", \
"ls_staticShipPart_base", \
"ls_staticShip_acclamator", \
"ls_staticShip_acclamator_landed", \
"ls_staticShip_acclamator_landed_hollow", \
"ls_staticShip_acclamator_hollow", \
"ls_staticShip_acclamator_landed_hollow_noRamp", \
"ls_staticShip_acclamator_landed_noRamp", \
"ls_staticShip_c9LightCruiser", \
"ls_staticShip_c9LightCruiser_republic", \
"ls_staticShip_c9LightCruiser_newRepublic", \
"ls_staticShip_coreShip", \
"ls_staticShipPart_coreShip_controlTower", \
"ls_staticShipPart_coreShip_core1", \
"ls_staticShipPart_coreShip_core2", \
"ls_staticShipPart_coreShip_core3", \
"ls_staticShipPart_coreShip_core4", \
"ls_staticShipPart_coreShip_platform1", \
"ls_staticShipPart_coreShip_platform2", \
"ls_staticShipPart_coreShip_platform3", \
"ls_staticShipPart_coreShip_platform4", \
"ls_staticShipPart_coreShip_radar", \
"ls_staticShip_dby827", \
"ls_staticShip_diamondClassCruiser", \
"ls_staticShip_diamondClassCruiser_cis", \
"ls_staticShip_fg40SupportFrigate", \
"ls_staticShip_hardcell", \
"ls_staticShipPart_hardcell_body", \
"ls_staticShipPart_hardcell_engine1", \
"ls_staticShipPart_hardcell_engine2", \
"ls_staticShipPart_hardcell_engine3", \
"ls_staticShipPart_hardcell_leg1", \
"ls_staticShipPart_hardcell_leg2", \
"ls_staticShipPart_hardcell_leg3", \
"ls_staticShip_lucrehulk", \
"ls_staticShipPart_lucrehulk_core1", \
"ls_staticShipPart_lucrehulk_core2", \
"ls_staticShipPart_lucrehulk_core3", \
"ls_staticShipPart_lucrehulk_back", \
"ls_staticShipPart_lucrehulk_bottom1", \
"ls_staticShipPart_lucrehulk_bottom2", \
"ls_staticShipPart_lucrehulk_bottom3", \
"ls_staticShipPart_lucrehulk_bottom4", \
"ls_staticShipPart_lucrehulk_engine", \
"ls_staticShipPart_lucrehulk_front1", \
"ls_staticShipPart_lucrehulk_front2", \
"ls_staticShipPart_lucrehulk_front3", \
"ls_staticShipPart_lucrehulk_front4", \
"ls_staticShipPart_lucrehulk_gate", \
"ls_staticShipPart_lucrehulk_inner1", \
"ls_staticShipPart_lucrehulk_inner2", \
"ls_staticShipPart_lucrehulk_inner3", \
"ls_staticShipPart_lucrehulk_inner4", \
"ls_staticShipPart_lucrehulk_radar1", \
"ls_staticShipPart_lucrehulk_radar2", \
"ls_staticShipPart_lucrehulk_radar3", \
"ls_staticShipPart_lucrehulk_radar4", \
"ls_staticShipPart_lucrehulk_top1", \
"ls_staticShipPart_lucrehulk_top2", \
"ls_staticShipPart_lucrehulk_top3", \
"ls_staticShipPart_lucrehulk_top4", \
"ls_staticShip_mandator", \
"ls_staticShipPart_mandator_body1_1", \
"ls_staticShipPart_mandator_body2_1", \
"ls_staticShipPart_mandator_body2_2", \
"ls_staticShipPart_mandator_body3_1", \
"ls_staticShipPart_mandator_body3_2", \
"ls_staticShipPart_mandator_body4_1", \
"ls_staticShipPart_mandator_body4_2", \
"ls_staticShipPart_mandator_body4_3", \
"ls_staticShipPart_mandator_body4_4", \
"ls_staticShipPart_mandator_body4_5", \
"ls_staticShipPart_mandator_body4_6", \
"ls_staticShipPart_mandator_body4_7", \
"ls_staticShipPart_mandator_body4_8", \
"ls_staticShipPart_mandator_engine1", \
"ls_staticShipPart_mandator_engine2", \
"ls_staticShipPart_mandator_engine3", \
"ls_staticShipPart_mandator_hanger1_1", \
"ls_staticShipPart_mandator_hanger2_1", \
"ls_staticShipPart_mandator_hanger2_2", \
"ls_staticShipPart_mandator_hanger3_1", \
"ls_staticShipPart_mandator_hanger3_2", \
"ls_staticShipPart_mandator_hanger4", \
"ls_staticShip_munificent", \
"ls_staticShip_providence", \
"ls_staticShip_providence_hollow", \
"ls_staticShip_providence_dreadnought", \
"ls_staticShip_providence_dreadnought_hollow", \
"ls_staticShipPart_providence_body1", \
"ls_staticShipPart_providence_body1_dreadnought", \
"ls_staticShipPart_providence_body2", \
"ls_staticShipPart_providence_body2_dreadnought", \
"ls_staticShipPart_providence_body3", \
"ls_staticShipPart_providence_body3_dreadnought", \
"ls_staticShipPart_providence_bridge", \
"ls_staticShipPart_providence_bridge_dreadnought", \
"ls_staticShipPart_providence_engine", \
"ls_staticShipPart_providence_engine_dreadnought", \
"ls_staticShipPart_providence_interior", \
"ls_staticShipPart_providence_interior_dreadnought", \
"ls_staticShip_providence_zeus", \
"ls_staticShip_providence_dreadnought_zeus", \
"ls_staticShip_quasar", \
"ls_staticShip_recusant", \
"ls_staticShip_recusant_dreadnought", \
"ls_staticShipPart_recusant_body1", \
"ls_staticShipPart_recusant_body1_dreadnought", \
"ls_staticShipPart_recusant_body2", \
"ls_staticShipPart_recusant_body2_dreadnought", \
"ls_staticShipPart_recusant_engine", \
"ls_staticShipPart_recusant_engine_dreadnought", \
"ls_staticShip_recusant_zeus", \
"ls_staticShip_recusant_zeus_dreadnought", \
"ls_staticShip_sdsStealthShip", \
"ls_staticShip_subjugator", \
"ls_staticShipPart_subjugator_body1", \
"ls_staticShipPart_subjugator_body1_1", \
"ls_staticShipPart_subjugator_body2", \
"ls_staticShipPart_subjugator_body2_1", \
"ls_staticShipPart_subjugator_body2_2", \
"ls_staticShipPart_subjugator_body2_3", \
"ls_staticShipPart_subjugator_body2_4", \
"ls_staticShipPart_subjugator_body3", \
"ls_staticShipPart_subjugator_body4", \
"ls_staticShipPart_subjugator_body4_1", \
"ls_staticShipPart_subjugator_body4_2", \
"ls_staticShipPart_subjugator_body4_3", \
"ls_staticShipPart_subjugator_body4_4", \
"ls_staticShipPart_subjugator_body5", \
"ls_staticShipPart_subjugator_body5_1", \
"ls_staticShipPart_subjugator_body5_2", \
"ls_staticShipPart_subjugator_body5_3", \
"ls_staticShipPart_subjugator_body5_4", \
"ls_staticShipPart_subjugator_bridge", \
"ls_staticShipPart_subjugator_emp1", \
"ls_staticShipPart_subjugator_emp1_1", \
"ls_staticShipPart_subjugator_emp2", \
"ls_staticShipPart_subjugator_emp2_1", \
"ls_staticShipPart_subjugator_engine", \
"ls_staticShip_venator", \
"ls_staticShip_venator_hollow", \
"ls_staticShip_venator_fullHollow", \
"ls_staticShip_venator_open", \
"ls_staticShip_venator_open_hollow", \
"ls_staticShip_venator_open_fullHollow", \
"ls_staticShipPart_venator_body1_1", \
"ls_staticShipPart_venator_body1_2", \
"ls_staticShipPart_venator_body2_1", \
"ls_staticShipPart_venator_body2_2", \
"ls_staticShipPart_venator_body2_3", \
"ls_staticShipPart_venator_body3", \
"ls_staticShipPart_venator_body4", \
"ls_staticShipPart_venator_body5", \
"ls_staticShipPart_venator_body6", \
"ls_staticShipPart_venator_body7", \
"ls_staticShipPart_venator_body8", \
"ls_staticShipPart_venator_body9", \
"ls_staticShipPart_venator_body10", \
"ls_staticShipPart_venator_door", \
"ls_staticShipPart_venator_doorOpen", \
"ls_staticShipPart_venator_engine", \
"ls_staticShipPart_venator_interior1", \
"ls_staticShipPart_venator_interior2", \
"ls_staticShipPart_venator_interior3", \
"ls_staticShipPart_venator_interior4", \
"ls_staticShipPart_venator_interior5", \
"ls_staticShipPart_venator_interior6", \
"ls_staticShipPart_venator_interior7", \
"ls_staticShipPart_venator_interior8", \
"ls_staticShipPart_venator_bridge", \
"ls_staticShip_venator_zeus", \
"ls_staticShip_administratorClassCarrier"

#undef WEAPONS_LIST
#define WEAPONS_LIST
