
#undef WEAPONS_LIST
#define WEAPONS_LIST \
"ls_droidHelmet_b1", \
"ls_droidHelmet_b1_geonosis", \
"ls_droidHelmet_b1_training", \
"ls_droidHelmet_b1_saboteur", \
"ls_droidHelmet_b1_firefighter", \
"ls_droidHelmet_b1_advanced", \
"ls_droidHelmet_b1_scout", \
"ls_droidHelmet_b1_scout_geonosis", \
"ls_droidHelmet_b1_grenadier", \
"ls_droidHelmet_b1_grenadier_geonosis", \
"ls_droidHelmet_b1_commander", \
"ls_droidHelmet_b1_commander_geonosis", \
"ls_droidHelmet_b1_crew", \
"ls_droidHelmet_b1_crew_geonosis", \
"ls_droidHelmet_b1_hologram", \
"ls_droidHelmet_b1_simulation", \
"ls_droidUniform_b1", \
"ls_droidUniform_b1_geonosis", \
"ls_droidUniform_b1_training", \
"ls_droidUniform_b1_advanced", \
"ls_droidUniform_b1_heavy", \
"ls_droidUniform_b1_heavy_geonosis", \
"ls_droidUniform_b1_grenadier", \
"ls_droidUniform_b1_grenadier_geonosis", \
"ls_droidUniform_b1_scout", \
"ls_droidUniform_b1_scout_geonosis", \
"ls_droidUniform_b1_firefighter", \
"ls_droidUniform_b1_marine", \
"ls_droidUniform_b1_engineer", \
"ls_droidUniform_b1_engineer_geonosis", \
"ls_droidUniform_b1_commander", \
"ls_droidUniform_b1_commander_advanced", \
"ls_droidUniform_b1_commander_geonosis", \
"ls_droidUniform_b1_saboteur", \
"ls_droidUniform_b1_crew", \
"ls_droidUniform_b1_crew_geonosis", \
"ls_droidUniform_b1_pilot", \
"ls_droidUniform_b1_pilot_geonosis", \
"ls_droidUniform_b1_security", \
"ls_droidUniform_b1_security_geonosis", \
"ls_droidUniform_b1_junkyard", \
"ls_droidUniform_b1_hologram", \
"ls_droidUniform_b1_simulation", \
"ls_droidUniform_b2", \
"ls_droidUniform_b2_hologram", \
"ls_droidUniform_b2_simulation", \
"ls_droidUniform_b2_junkyard", \
"ls_droidUniform_bx", \
"ls_droidUniform_bx_activeCamo", \
"ls_droidUniform_bx_hologram", \
"ls_droidUniform_bx_simulation", \
"ls_droidUniform_bx_captain", \
"ls_droidUniform_bx_security", \
"ls_droidUniform_bx_diplomat", \
"ls_droidUniform_bx_training", \
"ls_droidUniform_bx_bountyHunter", \
"ls_droidUniform_bx_junkyard", \
"ls_droidUniform_bx_cloneDisguise", \
"ls_droidUniform_droideka", \
"ls_droidUniform_droideka_training", \
"ls_droidUniform_droideka_imperial", \
"ls_droidUniform_droideka_junkyard"

#undef UNITS_LIST
#define UNITS_LIST \
"ls_droid_b1", \
"ls_droid_b1_advanced", \
"ls_droid_b1_geonosis", \
"ls_droid_b1_training", \
"ls_droid_b1_saboteur", \
"ls_droid_b1_firefighter", \
"ls_droid_b1_scout", \
"ls_droid_b1_scout_geonosis", \
"ls_droid_b1_marine", \
"ls_droid_b1_crew", \
"ls_droid_b1_crew_geonosis", \
"ls_droid_b1_engineer", \
"ls_droid_b1_engineer_geonosis", \
"ls_droid_b1_grenadier", \
"ls_droid_b1_grenadier_geonosis", \
"ls_droid_b1_grenadier_training", \
"ls_droid_b1_grenadier_advanced", \
"ls_droid_b1_heavy", \
"ls_droid_b1_heavy_geonosis", \
"ls_droid_b1_heavy_training", \
"ls_droid_b1_heavy_advanced", \
"ls_droid_b1_oom_base", \
"ls_droid_b1_commander", \
"ls_droid_b1_commander_geonosis", \
"ls_droid_b1_commander_advanced", \
"ls_droid_b1_pilot", \
"ls_droid_b1_pilot_geonosis", \
"ls_droid_b1_security", \
"ls_droid_b1_security_geonosis", \
"ls_droid_b1_junkyard", \
"ls_droid_b1_hologram", \
"ls_droid_b1_simulation", \
"ls_droid_b1_breacher", \
"ls_droid_b1_breacher_geonosis", \
"ls_droid_b1_breacher_training", \
"ls_droid_b1_breacher_advanced", \
"ls_droid_b1_marksman", \
"ls_droid_b1_marksman_geonosis", \
"ls_droid_b1_marksman_training", \
"ls_droid_b1_marksman_advanced", \
"ls_droid_b1_squadLeader", \
"ls_droid_b1_squadLeader_geonosis", \
"ls_droid_b1_squadLeader_training", \
"ls_droid_b1_squadLeader_advanced", \
"ls_droid_b1_at", \
"ls_droid_b1_at_geonosis", \
"ls_droid_b1_at_training", \
"ls_droid_b1_at_advanced", \
"ls_droid_b1_heavyAT", \
"ls_droid_b1_heavyAT_geonosis", \
"ls_droid_b1_heavyAT_training", \
"ls_droid_b1_heavyAT_advanced", \
"ls_droid_b1_heavyAA", \
"ls_droid_b1_heavyAA_geonosis", \
"ls_droid_b1_heavyAA_training", \
"ls_droid_b1_heavyAA_advanced", \
"ls_droid_b2", \
"ls_droid_b2_hologram", \
"ls_droid_b2_simulation", \
"ls_droid_b2_junkyard", \
"ls_droid_bx", \
"ls_droid_bx_activeCamo", \
"ls_droid_bx_hologram", \
"ls_droid_bx_simulation", \
"ls_droid_bx_captain", \
"ls_droid_bx_security", \
"ls_droid_bx_diplomat", \
"ls_droid_bx_training", \
"ls_droid_bx_bountyHunter", \
"ls_droid_bx_junkyard", \
"ls_droid_bx_assassain", \
"ls_droid_bx_impostor", \
"ls_droid_bx_cloneDisguise_phase2", \
"ls_droid_bx_cloneDisguise_phase1", \
"ls_droid_droideka", \
"ls_droid_droideka_noShield", \
"ls_droid_droideka_training", \
"ls_droid_droideka_noShield_training", \
"ls_droid_droideka_imperial", \
"ls_droid_droideka_noShield_imperial", \
"ls_droid_droideka_junkyard", \
"ls_droid_droideka_noShield_junkyard", \
"ls_droidBackpack_base", \
"ls_droidBackpack_b1", \
"ls_droidBackpack_b1_geonosis", \
"ls_droidBackpack_b1_training", \
"ls_droidBackpack_b1_heavy", \
"ls_droidBackpack_b1_heavy_geonosis", \
"ls_droidBackpack_b1_grenadier", \
"ls_droidBackpack_b1_grenadier_geonosis", \
"ls_droidBackpack_b1_saboteur", \
"ls_droidBackpack_b1_firefighter", \
"ls_droidBackpack_b1_crew", \
"ls_droidBackpack_b1_crew_geonosis", \
"ls_droidBackpack_b1_pilot", \
"ls_droidBackpack_b1_pilot_geonosis", \
"ls_droidBackpack_b1_security", \
"ls_droidBackpack_b1_security_geonosis", \
"ls_droidBackpack_b1_marine", \
"ls_droidBackpack_b1_engineer", \
"ls_droidBackpack_b1_engineer_geonosis", \
"ls_droidBackpack_b1_hologram", \
"ls_droidBackpack_b1_simulation", \
"ls_droidBackpack_b1_antenna", \
"ls_droidBackpack_b1_antenna_geonosis", \
"ls_droidBackpack_b1_antenna_training", \
"ls_droidBackpack_b1_antenna_hologram", \
"ls_droidBackpack_b1_antenna_simulation", \
"ls_droidBackpack_b1_marine_predef_at", \
"ls_droidBackpack_b1_predef_at", \
"ls_droidBackpack_b1_geonosis_predef_at", \
"ls_droidBackpack_b1_training_predef_at", \
"ls_droidBackpack_b1_predef_heavyAT", \
"ls_droidBackpack_b1_geonosis_predef_heavyAT", \
"ls_droidBackpack_b1_training_predef_heavyAT", \
"ls_droidBackpack_b1_predef_heavyAA", \
"ls_droidBackpack_b1_geonosis_predef_heavyAA", \
"ls_droidBackpack_b1_training_predef_heavyAA", \
"ls_droidBackpack_b1_saboteur_predef_demo", \
"ls_droidHelmet_b1_GH", \
"ls_droidHelmet_b1_geonosis_GH", \
"ls_droidHelmet_b1_training_GH", \
"ls_droidHelmet_b1_saboteur_GH", \
"ls_droidHelmet_b1_firefighter_GH", \
"ls_droidHelmet_b1_scout_GH", \
"ls_droidHelmet_b1_scout_geonosis_GH", \
"ls_droidHelmet_b1_grenadier_GH", \
"ls_droidHelmet_b1_grenadier_geonosis_GH", \
"ls_droidHelmet_b1_commander_GH", \
"ls_droidHelmet_b1_commander_geonosis_GH", \
"ls_droidHelmet_b1_crew_GH", \
"ls_droidHelmet_b1_crew_geonosis_GH", \
"ls_droidHelmet_b1_hologram_GH", \
"ls_droidHelmet_b1_simulation_GH"
