
#undef WEAPONS_LIST
#define WEAPONS_LIST \
"ls_droidHelmet_b1", \
"ls_droidHelmet_b1_officer", \
"ls_droidHelmet_b1_hologram", \
"ls_droidHelmet_b1_simulation", \
"ls_droidHelmet_b1_geonosis", \
"ls_droidHelmet_b1_geonosisOfficer", \
"ls_droidHelmet_b1_training", \
"ls_droidHelmet_b1_saboteur", \
"ls_droidHelmet_b1_crew", \
"ls_droidUniform_b1", \
"ls_droidUniform_b1_officer", \
"ls_droidUniform_b1_hologram", \
"ls_droidUniform_b1_simulation", \
"ls_droidUniform_b1_geonosis", \
"ls_droidUniform_b1_geonosisOfficer", \
"ls_droidUniform_b1_training", \
"ls_droidUniform_b1_saboteur", \
"ls_droidUniform_b1_crew", \
"ls_droidUniform_b1_pilot", \
"ls_droidUniform_b1_security", \
"ls_droidUniform_b2", \
"ls_droidUniform_b2_hologram", \
"ls_droidUniform_b2_simulation", \
"ls_droidUniform_b2_junkyard", \
"ls_droidUniform_bx", \
"ls_droidUniform_bx_activeCamo", \
"ls_droidUniform_bx_hologram", \
"ls_droidUniform_bx_simulation", \
"ls_droidUniform_bx_captain", \
"ls_droidUniform_bx_security", \
"ls_droidUniform_bx_diplomat", \
"ls_droidUniform_bx_cloneDisguise"

#undef UNITS_LIST
#define UNITS_LIST \
"ls_droid_b1", \
"ls_droid_b1_officer", \
"ls_droid_b1_hologram", \
"ls_droid_b1_simulation", \
"ls_droid_b1_geonosis", \
"ls_droid_b1_geonosisOfficer", \
"ls_droid_b1_training", \
"ls_droid_b1_saboteur", \
"ls_droid_b1_oom_base", \
"ls_droid_b1_crew", \
"ls_droid_b1_pilot", \
"ls_droid_b1_security", \
"ls_droid_b1_heavy", \
"ls_droid_b1_shotgun", \
"ls_droid_b1_geonosisShotgun", \
"ls_droid_b1_trainingShotgun", \
"ls_droid_b1_geonosisHeavy", \
"ls_droid_b1_trainingHeavy", \
"ls_droid_b1_marksman", \
"ls_droid_b1_geonosisMarksman", \
"ls_droid_b1_trainingMarksman", \
"ls_droid_b1_grenadier", \
"ls_droid_b1_geonosisGrenadier", \
"ls_droid_b1_trainingGrenadier", \
"ls_droid_b1_squadLeader", \
"ls_droid_b1_geonosisSquadLeader", \
"ls_droid_b1_trainingSquadLeader", \
"ls_droid_b1_at", \
"ls_droid_b1_geonosisAT", \
"ls_droid_b1_trainingAT", \
"ls_droid_b1_heavyAT", \
"ls_droid_b1_geonosisHeavyAT", \
"ls_droid_b1_trainingHeavyAT", \
"ls_droid_b1_heavyAA", \
"ls_droid_b1_geonosisHeavyAA", \
"ls_droid_b1_trainingHeavyAA", \
"ls_droid_b2", \
"ls_droid_b2_hologram", \
"ls_droid_b2_simulation", \
"ls_droid_b2_junkyard", \
"ls_droid_bx", \
"ls_droid_bx_activeCamo", \
"ls_droid_bx_hologram", \
"ls_droid_bx_simulation", \
"ls_droid_bx_captain", \
"ls_droid_bx_security", \
"ls_droid_bx_diplomat", \
"ls_droid_bx_assassain", \
"ls_droid_bx_cloneDisguise_phase2", \
"ls_droid_bx_cloneDisguise_phase1", \
"ls_droidBackpack_base", \
"ls_droidBackpack_b1", \
"ls_droidBackpack_b1_hologram", \
"ls_droidBackpack_b1_simulation", \
"ls_droidBackpack_b1_crew", \
"ls_droidBackpack_b1_geonosis", \
"ls_droidBackpack_b1_training", \
"ls_droidBackpack_b1_antenna", \
"ls_droidBackpack_b1_antenna_hologram", \
"ls_droidBackpack_b1_antenna_simulation", \
"ls_droidBackpack_b1_antenna_geonosis", \
"ls_droidBackpack_b1_antenna_training", \
"ls_droidBackpack_b1_predef_at", \
"ls_droidBackpack_b1_geonosis_predef_at", \
"ls_droidBackpack_b1_training_predef_at", \
"ls_droidBackpack_b1_predef_heavyAT", \
"ls_droidBackpack_b1_geonosis_predef_heavyAT", \
"ls_droidBackpack_b1_training_predef_heavyAT", \
"ls_droidBackpack_b1_predef_heavyAA", \
"ls_droidBackpack_b1_geonosis_predef_heavyAA", \
"ls_droidBackpack_b1_training_predef_heavyAA", \
"ls_droidBackpack_b1_predef_saboteur", \
"ls_droidHelmet_b1_GH", \
"ls_droidHelmet_b1_officer_GH", \
"ls_droidHelmet_b1_hologram_GH", \
"ls_droidHelmet_b1_simulation_GH", \
"ls_droidHelmet_b1_geonosis_GH", \
"ls_droidHelmet_b1_geonosisOfficer_GH", \
"ls_droidHelmet_b1_training_GH", \
"ls_droidHelmet_b1_saboteur_GH", \
"ls_droidHelmet_b1_crew_GH", \
"ls_helmet_droid_b1_geonosisOfficer_GH"
