#undef UNITS_LIST
#define UNITS_LIST \
"ls_clone_5th_trooper", \
"ls_clone_5th_medic", \
"ls_clone_5th_nco", \
"ls_clone_5th_officer", \
"ls_clone_13th_trooper", \
"ls_clone_21st_trooper", \
"ls_clone_21st_officer", \
"ls_clone_34th_trooper", \
"ls_clone_41st_trooper", \
"ls_clone_41st_officer", \
"ls_clone_phase2_41st_gree", \
"ls_clone_41stgc_trooper", \
"ls_clone_phase2_41strb_trooper", \
"ls_clone_scout_41strb_trooper", \
"ls_clone_74th_trooper", \
"ls_clone_91st_trooper", \
"ls_clone_91st_medic", \
"ls_clone_101st_trooper", \
"ls_clone_101st_doom", \
"ls_clone_104th_trooper", \
"ls_clone_104th_wolffe", \
"ls_clone_187th_trooper", \
"ls_clone_187th_officer", \
"ls_clone_212th_trooper", \
"ls_clone_212th_airborne", \
"ls_clone_212th_boil", \
"ls_clone_212th_waxer", \
"ls_clone_marshalCommander_212th_cody", \
"ls_clone_327th_trooper", \
"ls_clone_327th_bly", \
"ls_clone_332nd_trooper", \
"ls_clone_442nd_trooper", \
"ls_clone_501st_echo", \
"ls_clone_501st_fives", \
"ls_clone_501st_hardcase", \
"ls_clone_501st_jesse", \
"ls_clone_501st_rex", \
"ls_clone_501st_dogma", \
"ls_clone_501st_tup", \
"ls_clone_501st_kix", \
"ls_clone_501st_trooper", \
"ls_clone_612th_trooper", \
"ls_clone_612th_ganch", \
"ls_clone_coruscantguard_trooper", \
"ls_clone_coruscantguard_thorn", \
"ls_clone_coruscantguard_fox", \
"ls_clone_horncompany_trooper", \
"ls_clone_horncompany_lock", \
"ls_clone_kcompany_trooper", \
"ls_clone_kcompany_deviss", \
"ls_clone_rancor_trooper", \
"ls_clone_rancor_colt", \
"ls_clone_rancor_blitz", \
"ls_clone_rancor_havoc", \
"ls_clone_misc_fordo", \
"ls_clone_misc_eod", \
"ls_clone_misc_commander", \
"ls_clone_misc_captain", \
"ls_clone_misc_lieutenant", \
"ls_clone_misc_sergeant"

#undef WEAPONS_LIST
#define WEAPONS_LIST ""
