class ls_mandalorian_male {
    class FirstNames {
        boba = "Boba";
        jango = "Jango";
        cassus = "Cassus";
        jaster = "Jaster";
        fenn = "Fenn";
        tobbi = "Tobbi";
        kal = "Kal";
        wade = "Wad'e";
        goran = "Goran";
        mij = "Mij";
        kad = "Kad";
        venku = "Venku";
        munin = "Munin";
        ijaat = "Ijaat";
        tor = "Tor";
        pre = "Pre";
        montross = "Montross";
        lorka = "Lorka";
        teti = "Teti";
        fenri = "Fenri";
        hutu = "Hutu";
        dred = "Dred";
        akaavi = "Akaavi";
        akero = "Akero";
        barin = "B'arin";
        briike = "Briike";
        cikartan = "Cikartan";
        chopaa = "Cho'paa";
        ches = "Ghes";
        rako = "Rako";
        makin = "Makin";
        vorten = "Vorten";
        rogaar = "Rogaar";
        ghez = "Ghez";
        hayar = "Hayar";
        jaing = "Jaing";
        canderous = "Canderous";
        rohlan = "Rohlan";
        demagol = "Demagol";
        jarkyc = "Jarkyc";
        rook = "Rook";
        valen = "Valen";
        novin = "Novin";
        sedyn = "Sedyn";
        deth = "Deth";
        bossan = "Bossan";
        gar = "Gar";
        akshae = "Akshae";
        ram = "Ram";
        llats = "Llats";
        feskitt = "Feskitt";
        tiroc = "Tiroc";
        cham = "Cham";
        suvar = "Suvar";
        jakal = "Jakal";
        parma = "Parma";
        belok = "Belok";
        scarn = "Scarn";
        tem = "Tem";
        orar = "Orar";
        galaar = "Galaar";
        parjai = "Parjai";
    };
    class LastNames {
        fett = "Fett";
        ordo = "Ordo";
        vau = "Vau";
        skirata = "Skirata";
        shan = "Shan";
        kryze = "Kryze";
        viszla = "Viszla";
        cadera = "Cadera";
        kandosii = "Kandosii";
    };
};

// class ls_mandalorian_female: {
//     class FirstNames {
//     };
// };
