#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        author = AUTHOR;
        authors[] = {"DartRuffian"};
        name = COMPONENT_NAME;
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "ls_activecamo",
            "ls_animations",
            "ls_characters",
            "ls_characters_civilian",
            "ls_characters_clone",
            "ls_characters_clone_legacy",
            "ls_characters_clone_legions",
            "ls_characters_csf",
            "ls_characters_droid",
            "ls_characters_imperial",
            "ls_characters_jabiim",
            "ls_characters_mandalorian",
            "ls_characters_meme",
            "ls_characters_orsf",
            "ls_characters_rebels",
            "ls_common",
            "ls_data",
            "ls_dispenser",
            "ls_dubbing",
            "ls_equipment",
            "ls_groups",
            "ls_holoprojector",
            "ls_identities",
            "ls_impulsor",
            "ls_jetpacks",
            "ls_lighting",
            "ls_main",
            "ls_meme",
            "ls_modules",
            "ls_props",
            "ls_props_staticships",
            "ls_props_structures",
            "ls_props_tibanna",
            "ls_radios",
            "ls_sounds",
            "ls_vehicles",
            "ls_vehicles_105k",
            "ls_vehicles_aat",
            "ls_vehicles_agt",
            "ls_vehicles_ast",
            "ls_vehicles_barc",
            "ls_vehicles_bawhag",
            "ls_vehicles_cisdropship",
            "ls_vehicles_cr88",
            "ls_vehicles_hmp",
            "ls_vehicles_j10",
            "ls_vehicles_laatc",
            "ls_vehicles_laati",
            "ls_vehicles_laatle",
            "ls_vehicles_mortar",
            "ls_vehicles_mrbc",
            "ls_vehicles_mtt",
            "ls_vehicles_radardish",
            "ls_vehicles_starsaber",
            "ls_vehicles_stealthbox",
            "ls_vehicles_tx130",
            "ls_vehicles_z95",
            "ls_vehicles_z98",
            "ls_weapons",
            "ls_weapons_dcseries",
            "ls_weapons_eseries",
            "ls_weapons_explosives",
            "ls_weapons_firepuncher",
            "ls_weapons_grenades",
            "ls_weapons_melee",
            "ls_weapons_mercenary",
            "ls_weapons_mpl",
            "ls_weapons_plx",
            "ls_weapons_rd4",
            "ls_weapons_repeaters",
            "ls_weapons_rg4d",
            "ls_weapons_rps",
            "ls_weapons_westar",
            "ls_weapons_zh73",
            "ls_weapons_zseries"
        };
        units[] = {};
        weapons[] = {};
        VERSION_CONFIG;
    };
};
