#undef UNITS_LIST
#undef WEAPONS_LIST

#define UNITS_LIST \
"ls_imperialHelmet_army_GH", \
"ls_imperialHelmet_army_gd_GH", \
"ls_imperialHelmet_army_gu_GH", \
"ls_imperialHelmet_army_gdr_GH", \
"ls_imperialHelmet_army_gur_GH", \
"ls_imperialHelmet_kepi_GH", \
"ls_imperialHelmet_kepi_black_GH", \
"ls_imperialHelmet_kepi_isb_GH", \
"ls_imperialHelmet_kepi_mudtrooper_GH", \
"ls_imperialHelmet_kepi_g_GH", \
"ls_imperialHelmet_kepi_g_black_GH", \
"ls_imperialHelmet_kepi_g_mudtrooper_GH", \
"ls_imperialHelmet_kepi_g_isb_GH", \
"ls_imperial_army_trooper", \
"ls_imperial_army_trooper_black", \
"ls_imperial_army_trooper_mudtrooper", \
"ls_imperial_army_trooper_isb", \
"ls_imperial_army_r", \
"ls_imperial_army_r_black", \
"ls_imperial_army_r_mudtrooper", \
"ls_imperial_army_r_isb", \
"ls_imperial_army_armored", \
"ls_imperial_army_armored_black", \
"ls_imperial_army_armored_mudtrooper", \
"ls_imperial_army_armored_isb", \
"ls_imperial_army_armored_r", \
"ls_imperial_army_armored_r_black", \
"ls_imperial_army_armored_r_mudtrooper", \
"ls_imperial_army_armored_r_isb", \
"ls_imperialBackpack_chestRig", \
"ls_imperialBackpack_chestRigPouch", \
"ls_imperialBackpack_satchel", \
"ls_imperialBackpack_shoulderPouch", \
"ls_imperial_army_heavy", \
"ls_imperial_army_heavy_r", \
"ls_imperial_army_heavy_mudtrooper", \
"ls_imperial_army_heavy_mudtrooper_r", \
"ls_imperial_army_heavy_black", \
"ls_imperial_army_heavy_black_r", \
"ls_imperial_army_heavy_ISB", \
"ls_imperial_army_heavy_ISB_r", \
"ls_imperial_army_Shotgun", \
"ls_imperial_army_Shotgun_r", \
"ls_imperial_army_shotgun_mudtrooper", \
"ls_imperial_army_shotgun_mudtrooper_r", \
"ls_imperial_army_shotgun_black", \
"ls_imperial_army_shotgun_black_r", \
"ls_imperial_army_shotgun_ISB", \
"ls_imperial_army_shotgun_ISB_r", \
"ls_imperial_army_marksman", \
"ls_imperial_army_marksman_r", \
"ls_imperial_army_marksman_black", \
"ls_imperial_army_marksman_black_r", \
"ls_imperial_army_marksman_mudtrooper", \
"ls_imperial_army_marksman_mudtrooper_r", \
"ls_imperial_army_marksman_ISB", \
"ls_imperial_army_marksman_ISB_r", \
"ls_imperial_army_grenadier", \
"ls_imperial_army_grenadier_r", \
"ls_imperial_army_grenadier_black", \
"ls_imperial_army_grenadier_black_r", \
"ls_imperial_army_grenadier_mudtrooper", \
"ls_imperial_army_grenadier_mudtrooper_r", \
"ls_imperial_army_grenadier_ISB", \
"ls_imperial_army_grenadier_ISB_r", \
"ls_imperial_army_squadleader", \
"ls_imperial_army_squadleader_r", \
"ls_imperial_army_squadleader_black", \
"ls_imperial_army_squadleader_black_r", \
"ls_imperial_army_squadleader_mudtrooper", \
"ls_imperial_army_squadleader_mudtrooper_r", \
"ls_imperial_army_squadleader_ISB", \
"ls_imperial_army_squadleader_ISB_r", \
"ls_imperial_army_at", \
"ls_imperial_army_at_r", \
"ls_imperial_army_at_black", \
"ls_imperial_army_at_black_r", \
"ls_imperial_army_at_mudtrooper", \
"ls_imperial_army_at_mudtrooper_r", \
"ls_imperial_army_at_ISB", \
"ls_imperial_army_at_ISB_r", \
"ls_imperial_army_HeavyAT", \
"ls_imperial_army_HeavyAT_r", \
"ls_imperial_army_heavyAT_black", \
"ls_imperial_army_HeavyAT_black_r", \
"ls_imperial_army_HeavyAT_mudtrooper", \
"ls_imperial_army_HeavyAT_mudtrooper_r", \
"ls_imperial_army_HeavyAT_ISB", \
"ls_imperial_army_HeavyAT_ISB_r", \
"ls_imperial_army_HeavyAA", \
"ls_imperial_army_HeavyAA_r", \
"ls_imperial_army_HeavyAA_black", \
"ls_imperial_army_HeavyAA_black_r", \
"ls_imperial_army_HeavyAA_mudtrooper", \
"ls_imperial_army_HeavyAA_mudtrooper_r", \
"ls_imperial_army_HeavyAA_ISB", \
"ls_imperial_army_HeavyAA_ISB_r", \
"ls_imperial_army_officer", \
"ls_imperial_army_officer_black", \
"ls_imperial_army_officer_mudtrooper", \
"ls_imperial_army_officer_r", \
"ls_imperial_army_officer_black_r", \
"ls_imperial_army_officer_mudtrooper_r", \
"ls_imperial_army_medic", \
"ls_imperial_army_medic_black", \
"ls_imperial_army_medic_mudtrooper", \
"ls_imperial_army_medic_r", \
"ls_imperial_army_medic_black_r", \
"ls_imperial_army_medic_mudtrooper_r"

#define WEAPONS_LIST \
"ls_imperialHelmet_army", \
"ls_imperialHelmet_army_gd", \
"ls_imperialHelmet_army_gu", \
"ls_imperialHelmet_army_gdr", \
"ls_imperialHelmet_army_gur", \
"ls_imperialHelmet_kepi", \
"ls_imperialHelmet_kepi_black", \
"ls_imperialHelmet_kepi_isb", \
"ls_imperialHelmet_kepi_mudtrooper", \
"ls_imperialHelmet_kepi_g", \
"ls_imperialHelmet_kepi_g_black", \
"ls_imperialHelmet_kepi_g_mudtrooper", \
"ls_imperialHelmet_kepi_g_isb", \
"ls_imperialUniform_army_trooper", \
"ls_imperialUniform_army_trooper_black", \
"ls_imperialUniform_army_trooper_mudtrooper", \
"ls_imperialUniform_army_trooper_isb", \
"ls_imperialUniform_army_r", \
"ls_imperialUniform_army_r_black", \
"ls_imperialUniform_army_r_mudtrooper", \
"ls_imperialUniform_army_r_isb", \
"ls_imperialUniform_army_armored", \
"ls_imperialUniform_army_armored_black", \
"ls_imperialUniform_army_armored_mudtrooper", \
"ls_imperialUniform_army_armored_isb", \
"ls_imperialUniform_army_armored_r", \
"ls_imperialUniform_army_armored_r_black", \
"ls_imperialUniform_army_armored_r_mudtrooper", \
"ls_imperialUniform_army_armored_r_isb", \
"ls_imperialVest_stormtrooperPauldron", \
"ls_imperialVest_stormtrooperPauldron_black", \
"ls_imperialVest_stormtrooperPauldron_white", \
"ls_imperialVest_stormtrooperPauldron_whiplash", \
"ls_imperialVest_army", \
"ls_imperialVest_medic", \
"ls_imperialVest_officer", \
"ls_imperialVest_army_black", \
"ls_imperialVest_officer_black", \
"ls_imperialVest_medic_black", \
"ls_imperialVest_army_ISB", \
"ls_imperialVest_army_mudtrooper", \
"ls_imperialVest_medic_mudtrooper", \
"ls_imperialVest_officer_mudtrooper",\
"ls_imperialVest_army_h", \
"ls_imperialVest_medic_h", \
"ls_imperialVest_officer_h", \
"ls_imperialVest_army_black_h", \
"ls_imperialVest_medic_black_h", \
"ls_imperialVest_officer_black_h",\
"ls_imperialVest_army_ISB_h", \
"ls_imperialVest_army_mudtrooper_h", \
"ls_imperialVest_medic_mudtrooper_h", \
"ls_imperialVest_officer_mudtrooper_h",\
"ls_imperialVest_army_damaged", \
"ls_imperialVest_medic_damaged", \
"ls_imperialVest_officer_damaged", \
"ls_imperialVest_mudtrooper_damaged",\
"ls_imperialVest_army_light", \
"ls_imperialVest_medic_light", \
"ls_imperialVest_officer_light", \
"ls_imperialVest_army_light_black", \
"ls_imperialVest_medic_light_black", \
"ls_imperialVest_officer_light_black", \
"ls_imperialVest_army_light_ISB", \
"ls_imperialVest_army_light_mudtrooper", \
"ls_imperialVest_medic_light_mudtrooper", \
"ls_imperialVest_officer_light_mudtrooper",\
"ls_imperialVest_army_light_h", \
"ls_imperialVest_medic_light_h", \
"ls_imperialVest_officer_light_h", \
"ls_imperialVest_army_light_black_h", \
"ls_imperialVest_medic_light_black_h", \
"ls_imperialVest_officer_light_black_h", \
"ls_imperialVest_army_light_ISB_h", \
"ls_imperialVest_army_light_mudtrooper_h", \
"ls_imperialVest_medic_light_mudtrooper_h", \
"ls_imperialVest_officer_light_mudtrooper_h", \
"ls_imperialVest_army_medium", \
"ls_imperialVest_medic_medium", \
"ls_imperialVest_officer_medium", \
"ls_imperialVest_army_medium_black", \
"ls_imperialVest_medic_medium_black", \
"ls_imperialVest_officer_medium_black", \
"ls_imperialVest_army_medium_ISB", \
"ls_imperialVest_army_medium_mudtrooper", \
"ls_imperialVest_medic_medium_mudtrooper", \
"ls_imperialVest_officer_medium_mudtrooper", \
"ls_imperialVest_army_medium_h", \
"ls_imperialVest_medic_medium_h", \
"ls_imperialVest_officer_medium_h", \
"ls_imperialVest_army_medium_black_h", \
"ls_imperialVest_officer_medium_black_h", \
"ls_imperialVest_medic_medium_black_h", \
"ls_imperialVest_army_medium_ISB_h", \
"ls_imperialVest_army_medium_mudtrooper_h", \
"ls_imperialVest_medic_medium_mudtrooper_h", \
"ls_imperialVest_officer_medium_mudtrooper_h", \
"ls_imperialVest_army_tacbelt", \
"ls_imperialVest_army_tacbelt_black", \
"ls_imperialVest_army_tacbelt_mudtrooper", \
"ls_imperialVest_army_tacbelt_isb", \
