#undef UNITS_LIST
#undef WEAPONS_LIST

#define UNITS_LIST \
"ls_imperialHelmet_army_GH", \
"ls_imperialHelmet_army_gd_GH", \
"ls_imperialHelmet_army_gu_GH", \
"ls_imperialHelmet_army_gdr_GH", \
"ls_imperialHelmet_army_gur_GH", \
"ls_imperialHelmet_kepi_GH", \
"ls_imperialHelmet_kepi_black_GH", \
"ls_imperialHelmet_kepi_isb_GH", \
"ls_imperialHelmet_kepi_mudtrooper_GH", \
"ls_imperialHelmet_kepi_g_GH", \
"ls_imperialHelmet_kepi_g_black_GH", \
"ls_imperialHelmet_kepi_g_mudtrooper_GH", \
"ls_imperialHelmet_kepi_g_isb_GH", \
"ls_imperial_army_trooper", \
"ls_imperial_army_trooper_black", \
"ls_imperial_army_trooper_mudtrooper", \
"ls_imperial_army_trooper_isb", \
"ls_imperial_army_r", \
"ls_imperial_army_r_black", \
"ls_imperial_army_r_mudtrooper", \
"ls_imperial_army_r_isb", \
"ls_imperial_army_armored", \
"ls_imperial_army_armored_black", \
"ls_imperial_army_armored_mudtrooper", \
"ls_imperial_army_armored_isb", \
"ls_imperial_army_armored_r", \
"ls_imperial_army_armored_r_black", \
"ls_imperial_army_armored_r_mudtrooper", \
"ls_imperial_army_armored_r_isb", \
"ls_imperialBackpack_chestRig", \
"ls_imperialBackpack_chestRigPouch", \
"ls_imperialBackpack_satchel", \
"ls_imperialBackpack_shoulderPouch"

#define WEAPONS_LIST \
"ls_imperialHelmet_army", \
"ls_imperialHelmet_army_gd", \
"ls_imperialHelmet_army_gu", \
"ls_imperialHelmet_army_gdr", \
"ls_imperialHelmet_army_gur", \
"ls_imperialHelmet_kepi", \
"ls_imperialHelmet_kepi_black", \
"ls_imperialHelmet_kepi_isb", \
"ls_imperialHelmet_kepi_mudtrooper", \
"ls_imperialHelmet_kepi_g", \
"ls_imperialHelmet_kepi_g_black", \
"ls_imperialHelmet_kepi_g_mudtrooper", \
"ls_imperialHelmet_kepi_g_isb", \
"ls_imperialUniform_army_trooper", \
"ls_imperialUniform_army_trooper_black", \
"ls_imperialUniform_army_trooper_mudtrooper", \
"ls_imperialUniform_army_trooper_isb", \
"ls_imperialUniform_army_r", \
"ls_imperialUniform_army_r_black", \
"ls_imperialUniform_army_r_mudtrooper", \
"ls_imperialUniform_army_r_isb", \
"ls_imperialUniform_army_armored", \
"ls_imperialUniform_army_armored_black", \
"ls_imperialUniform_army_armored_mudtrooper", \
"ls_imperialUniform_army_armored_isb", \
"ls_imperialUniform_army_armored_r", \
"ls_imperialUniform_army_armored_r_black", \
"ls_imperialUniform_army_armored_r_mudtrooper", \
"ls_imperialUniform_army_armored_r_isb", \
"ls_imperialVest_stormtrooperPauldron", \
"ls_imperialVest_stormtrooperPauldron_black", \
"ls_imperialVest_stormtrooperPauldron_white", \
"ls_imperialVest_stormtrooperPauldron_whiplash", \
"ls_imperialVest_army", \
"ls_imperialVest_army_black", \
"ls_imperialVest_army_ISB", \
"ls_imperialVest_army_mudtrooper", \
"ls_imperialVest_army_h", \
"ls_imperialVest_army_black_h", \
"ls_imperialVest_army_ISB_h", \
"ls_imperialVest_army_mudtrooper_h", \
"ls_imperialVest_army_damaged", \
"ls_imperialVest_army_light", \
"ls_imperialVest_army_light_black", \
"ls_imperialVest_army_light_ISB", \
"ls_imperialVest_army_light_mudtrooper", \
"ls_imperialVest_army_light_h", \
"ls_imperialVest_army_light_black_h", \
"ls_imperialVest_army_light_ISB_h", \
"ls_imperialVest_army_light_mudtrooper_h", \
"ls_imperialVest_army_medium", \
"ls_imperialVest_army_medium_black", \
"ls_imperialVest_army_medium_ISB", \
"ls_imperialVest_army_medium_mudtrooper", \
"ls_imperialVest_army_medium_h", \
"ls_imperialVest_army_medium_black_h", \
"ls_imperialVest_army_medium_ISB_h", \
"ls_imperialVest_army_medium_mudtrooper_h", \
"ls_imperialVest_army_tacbelt", \
"ls_imperialVest_army_tacbelt_black", \
"ls_imperialVest_army_tacbelt_mudtrooper", \
"ls_imperialVest_army_tacbelt_isb", \
