#define MOVESET_SAFE(MOVESET_CLASS) \
    class DOUBLES(MOVESET_CLASS,safe): MOVESET_CLASS { \
        upDegree = "ManPosStand"; \
    }
#define STATE_SAFE(STATE_CLASS,MOVESET_CLASS) \
    class DOUBLES(STATE_CLASS,safe): STATE_CLASS { \
        actions = QUOTE(DOUBLES(MOVESET_CLASS,safe)); \
    }

#define MOVESET_NOWEAPON(MOVESET_CLASS) \
    class DOUBLES(MOVESET_CLASS,noWeapon): MOVESET_CLASS { \
        upDegree = "ManPosNoWeapon"; \
    }
#define STATE_NOWEAPON(STATE_CLASS,MOVESET_CLASS) \
    class DOUBLES(STATE_CLASS,noWeapon): STATE_CLASS { \
        actions = QUOTE(DOUBLES(MOVESET_CLASS,noWeapon)); \
    }

#define MOVESETS(MOVESET_CLASS) \
    MOVESET_SAFE(MOVESET_CLASS); \
    MOVESET_NOWEAPON(MOVESET_CLASS)

#define STATES(STATE_CLASS,MOVESET_CLASS) \
    STATE_SAFE(STATE_CLASS,MOVESET_CLASS); \
    STATE_NOWEAPON(STATE_CLASS,MOVESET_CLASS)
