class ls_AD3M_AAM: MissileBase {
    displayName = "AD-3M AAM";
    model = "\A3\Weapons_F\Ammo\Missile_AT_03_fly_F.p3d";
    proxyShape = "\A3\Weapons_F\Ammo\Missile_AT_03_F.p3d";
    hit = 200;
    indirectHit = 600;
    indirectHitRange = 7;
    proximityExplosionDistance = 5;
    explosive = 1;
    warheadName = "AAM";
    simulation = "shotMissile";
    simulationStep = 0.002;
    timeToLive = 75;
    initTime = 0.05;
    thrustTime = 8.25;
    thrust = 440;
    maxSpeed = 584;
    maneuvrability = 20;
    fuseDistance = 25;
    trackLead = 1;
    trackOversteer = 1.15;
    airFriction = 0.15;
    sideAirFriction = 0.1;
    cost = 500;
    class Components {
        class SensorsManagerComponent {
            class Components {
                class IRSensorComponent {
                    class AirTarget {
                        minRange = 100;
                        maxRange = 7000;
                        objectDistanceLimitCoef = -1;
                        viewDistanceLimitCoef = 1;
                    };
                    class GroundTarget {
                        minRange = 100;
                        maxRange = 7000;
                        objectDistanceLimitCoef = 1;
                        viewDistanceLimitCoef = 1;
                    };
                    maxTrackableSpeed = 1595;
                    angleRangeHorizontal = 30;
                    angleRangeVertical = 30;
                    componentType = "IRSensorComponent";
                    typeRecognitionDistance = 7000;
                    maxFogSeeThrough = 1;
                    color[] = {1,0,0,1};
                    allowsMarking = 1;
                    groundNoiseDistanceCoef = -1;
                    maxGroundNoiseDistance = -1;
                    minSpeedThreshold = 0;
                    maxSpeedThreshold = 0;
                    animDirection = "";
                    aimDown = 0;
                    minTrackableSpeed = -1e+10;
                    minTrackableATL = 75;
                    maxTrackableATL = 1e+10;
                };
            };
        };
    };
    missileLockCone = 60;
    missileKeepLockedCone = 60;
    missileLockMaxDistance = 5000;
    missileLockMinDistance = 100;
    missileLockMaxSpeed = 9000;
    irLock = 1;
    airLock = 2;
    aiAmmoUsageFlags = 128 + 512;
    dangerRadiusHit = 1000;
    suppressionRadiusHit = 120;
    craterEffects = "ATRocketCrater";
    explosionEffects = "ATRocketExplosion";
    explosionSoundEffect = "DefaultExplosion";
    effectsMissileInit = "RocketBackEffectsRPG";
    effectsMissile = "missile2";
    muzzleEffect = "";
    whistleDist = 4;
    lockType = 0;
    manualControl = 0;
    weaponLockSystem = "2";
    cmImmunity = 0.75;
    cameraViewAvailable = 1;
    submunitionAmmo = "";
    submunitionDirectionType = "SubmunitionModelDirection";
    submunitionInitSpeed = 1000;
    submunitionParentSpeedCoef = 0;
    submunitionInitialOffset[] = {0,0,-0.2};
    triggerOnImpact = 1;
    deleteParentWhenTriggered = 0;
};

class ls_148mm_Fletch_ATGM: MissileBase {
    displayName = "K-2M Fletch ATGM";
    scope = 2;
    model = "\A3\Weapons_F_Tank\Launchers\Vorona\Vorona_missile_heat_fly.p3d";
    proxyShape = "\A3\Weapons_F_Tank\Launchers\Vorona\Vorona_tube_heat";
    hit = 100;
    indirectHit = 20;
    indirectHitRange = 2.5;
    explosive = 0.4;
    warheadName = "ATGM";
    simulation = "shotMissile";
    simulationStep = 0.002;
    timeToLive = 30;
    initTime = 0.05;
    thrustTime = 15;
    thrust = 80;
    maxSpeed = 160;
    maneuvrability = 10;
    fuseDistance = 25;
    trackOversteer = 0.4;
    trackLead = 0.55;
    airFriction = 0;
    sideAirFriction = 0.1;
    cost = 500;
    aiAmmoUsageFlags = 128 + 512;
    dangerRadiusHit = 1000;
    suppressionRadiusHit = 120;
    craterEffects = "ATRocketCrater";
    explosionEffects = "ATRocketExplosion";
    explosionSoundEffect = "DefaultExplosion";
    effectsMissileInit = "RocketBackEffectsRPG";
    effectsMissile = "missile2";
    muzzleEffect = "";
    whistleDist = 4;
    airLock = 0;
    lockType = 1;
    manualControl = 0;
    class ace_missileguidance {
        enabled = 1;
        minDeflection = 0;
        maxDeflection = 0.001;
        incDeflection = 0.00015;
        canVanillaLock = 0;
        defaultSeekerType = "SACLOS";
        seekerTypes[] = {"SACLOS"};
        defaultSeekerLockMode = "LOAL";
        seekerLockModes[] = {"LOAL"};
        seekLastTargetPos = 0;
        seekerAngle = 60;
        seekerAccuracy = 1;
        seekerMinRange = 15;
        seekerMaxRange = 6000;
        correctionDistance = 3;
        offsetFromCrosshair[] = {0,0,0};
        defaultAttackProfile = "BEAM";
        attackProfiles[] = {"BEAM"};
    };
    maxControlRange = 6000;
    manualControlOffset = 100;
    missileManualControlCone = 40;
    weaponLockSystem = 0;
    cmImmunity = 1;
    cameraViewAvailable = 1;
    flightProfiles[] = {"Direct"};
    submunitionAmmo = "ls_ammo_Fletch_Penetrator";
    submunitionDirectionType = "SubmunitionModelDirection";
    submunitionInitSpeed = 1000;
    submunitionParentSpeedCoef = 0;
    submunitionInitialOffset[] = {0, 0, -0.2};
    triggerOnImpact = 1;
    deleteParentWhenTriggered = 0;
};
