#undef WEAPONS_LIST
#undef UNITS_LIST

#define WEAPONS_LIST ""

#define UNITS_LIST \
"ls_civilian_chiss_scientist", \
"ls_civilian_chiss_journalist", \
"ls_civilian_chiss_worker", \
"ls_civilian_chiss_pilot", \
"ls_civilian_chiss_polo1", \
"ls_civilian_chiss_polo2", \
"ls_civilian_chiss_polo3", \
"ls_civilian_chiss_polo4", \
"ls_civilian_chiss_polo5", \
"ls_civilian_chiss_polo6", \
"ls_civilian_chiss_officer", \
"ls_civilian_mirialan_scientist", \
"ls_civilian_mirialan_journalist", \
"ls_civilian_mirialan_worker", \
"ls_civilian_mirialan_pilot", \
"ls_civilian_mirialan_polo1", \
"ls_civilian_mirialan_polo2", \
"ls_civilian_mirialan_polo3", \
"ls_civilian_mirialan_polo4", \
"ls_civilian_mirialan_polo5", \
"ls_civilian_mirialan_polo6", \
"ls_civilian_mirialan_officer", \
"ls_civilian_randomSpecies_scientist", \
"ls_civilian_randomSpecies_journalist", \
"ls_civilian_randomSpecies_worker", \
"ls_civilian_randomSpecies_pilot", \
"ls_civilian_randomSpecies_polo1", \
"ls_civilian_randomSpecies_polo2", \
"ls_civilian_randomSpecies_polo3", \
"ls_civilian_randomSpecies_polo4", \
"ls_civilian_randomSpecies_polo5", \
"ls_civilian_randomSpecies_polo6", \
"ls_civilian_randomSpecies_officer", \
"ls_civilian_zabrak_scientist", \
"ls_civilian_zabrak_journalist", \
"ls_civilian_zabrak_worker", \
"ls_civilian_zabrak_pilot", \
"ls_civilian_zabrak_polo1", \
"ls_civilian_zabrak_polo2", \
"ls_civilian_zabrak_polo3", \
"ls_civilian_zabrak_polo4", \
"ls_civilian_zabrak_polo5", \
"ls_civilian_zabrak_polo6", \
"ls_civilian_zabrak_officer", \
"ls_civilian_zelosian_scientist", \
"ls_civilian_zelosian_journalist", \
"ls_civilian_zelosian_worker", \
"ls_civilian_zelosian_pilot", \
"ls_civilian_zelosian_polo1", \
"ls_civilian_zelosian_polo2", \
"ls_civilian_zelosian_polo3", \
"ls_civilian_zelosian_polo4", \
"ls_civilian_zelosian_polo5", \
"ls_civilian_zelosian_polo6", \
"ls_civilian_zelosian_officer", \
"ls_civilian_zeltron_scientist", \
"ls_civilian_zeltron_journalist", \
"ls_civilian_zeltron_worker", \
"ls_civilian_zeltron_pilot", \
"ls_civilian_zeltron_polo1", \
"ls_civilian_zeltron_polo2", \
"ls_civilian_zeltron_polo3", \
"ls_civilian_zeltron_polo4", \
"ls_civilian_zeltron_polo5", \
"ls_civilian_zeltron_polo6", \
"ls_civilian_zeltron_officer"
