#undef UNITS_LIST
#define UNITS_LIST \
"ls_mandalorian_base", \
"ls_mandalorian_protectorMale_base", \
"ls_mandalorian_traditionalWoman", \
"ls_mandalorian_traditionalWarrior", \
"ls_mandalorian_traditionalRTO", \
"ls_mandalorian_traditionalHeavy", \
"ls_mandalorian_traditionalMedic", \
"ls_mandalorian_traditionalMarksman", \
"ls_mandalorian_traditionalSupportGunner", \
"ls_mandalorian_traditionalAT", \
"ls_mandalorian_traditionalHeavyAT", \
"ls_mandalorian_traditionalHeavyAA", \
"ls_mandalorian_traditionalDemo", \
"ls_mandalorian_traditionalSergeant", \
"ls_mandalorian_traditionalCaptain", \
"ls_mandalorian_deathwatchWarrior", \
"ls_mandalorian_deathwatchRTO", \
"ls_mandalorian_deathwatchHeavy", \
"ls_mandalorian_deathwatchMedic", \
"ls_mandalorian_deathwatchMarksman", \
"ls_mandalorian_deathwatchSupportGunner", \
"ls_mandalorian_deathwatchAT", \
"ls_mandalorian_deathwatchHeavyAT", \
"ls_mandalorian_deathwatchHeavyAA", \
"ls_mandalorian_deathwatchDemo", \
"ls_mandalorian_deathwatchSergeant", \
"ls_mandalorian_deathwatchCaptain", \
"ls_mandalorian_eldarWarrior", \
"ls_mandalorian_eldarRTO", \
"ls_mandalorian_eldarHeavy", \
"ls_mandalorian_eldarMedic", \
"ls_mandalorian_eldarMarksman", \
"ls_mandalorian_eldarSupportGunner", \
"ls_mandalorian_eldarAT", \
"ls_mandalorian_eldarHeavyAT", \
"ls_mandalorian_eldarHeavyAA", \
"ls_mandalorian_eldarDemo", \
"ls_mandalorian_eldarSergeant", \
"ls_mandalorian_ordoWarrior", \
"ls_mandalorian_ordoRTO", \
"ls_mandalorian_ordoHeavy", \
"ls_mandalorian_ordoMedic", \
"ls_mandalorian_ordoMarksman", \
"ls_mandalorian_ordoSupportGunner", \
"ls_mandalorian_ordoAT", \
"ls_mandalorian_ordoHeavyAT", \
"ls_mandalorian_ordoHeavyAA", \
"ls_mandalorian_ordoDemo", \
"ls_mandalorian_ordoSergeant", \
"ls_mandalorian_saxonWarrior", \
"ls_mandalorian_saxonRTO", \
"ls_mandalorian_saxonHeavy", \
"ls_mandalorian_saxonMedic", \
"ls_mandalorian_saxonMarksman", \
"ls_mandalorian_saxonSupportGunner", \
"ls_mandalorian_saxonAT", \
"ls_mandalorian_saxonHeavyAT", \
"ls_mandalorian_saxonHeavyAA", \
"ls_mandalorian_saxonDemo", \
"ls_mandalorian_saxonSergeant", \
"ls_mandalorian_superCommandoWarrior", \
"ls_mandalorian_superCommandoRTO", \
"ls_mandalorian_superCommandoHeavy", \
"ls_mandalorian_superCommandoMedic", \
"ls_mandalorian_superCommandoMarksman", \
"ls_mandalorian_superCommandoSupportGunner", \
"ls_mandalorian_superCommandoAT", \
"ls_mandalorian_superCommandoHeavyAT", \
"ls_mandalorian_superCommandoHeavyAA", \
"ls_mandalorian_superCommandoDemo", \
"ls_mandalorian_superCommandoSergeant", \
"ls_mandalorian_superCommandoCaptain", \
"ls_mandalorian_vizslaWarrior", \
"ls_mandalorian_vizslaRTO", \
"ls_mandalorian_vizslaHeavy", \
"ls_mandalorian_vizslaMedic", \
"ls_mandalorian_vizslaMarksman", \
"ls_mandalorian_vizslaSupportGunner", \
"ls_mandalorian_vizslaAT", \
"ls_mandalorian_vizslaHeavyAT", \
"ls_mandalorian_vizslaHeavyAA", \
"ls_mandalorian_vizslaDemo", \
"ls_mandalorian_vizslaSergeant", \
"ls_mandalorian_vizslaCaptain", \
"ls_mandalorianBackpack_journeyman", \
"ls_mandalorianBackpack_light", \
"ls_mandalorianBackpack_medic", \
"ls_mandalorianBackpack_radio", \
"ls_mandalorianBackpack_predef_marksman", \
"ls_mandalorianBackpack_radio_predef_rto", \
"ls_mandalorianBackpack_medic_predef_medic", \
"ls_mandalorianBackpack", \
"ls_mandalorianBackpack_demo", \
"ls_mandalorianBackpack_heavy", \
"ls_mandalorianBackpack_predef_standard", \
"ls_mandalorianBackpack_heavy_predef_heavy", \
"ls_mandalorianBackpack_heavy_predef_machineGunner", \
"ls_mandalorianBackpack_heavy_predef_engineer", \
"ls_mandalorianBackpack_demo_predef_demo", \
"ls_mandalorianHelmet_armorer_GH", \
"ls_mandalorianHelmet_dinDjarin_GH", \
"ls_mandalorianHelmet_dinDjarin_beskar_GH", \
"ls_mandalorianHelmet_elite_GH", \
"ls_mandalorianHelmet_executioner_GH", \
"ls_mandalorianHelmet_nightowl_GH", \
"ls_mandalorianHelmet_stalker_GH", \
"ls_mandalorianHelmet_traditional_GH", \
"ls_mandalorianHelmet_eldarGrunt_GH", \
"ls_mandalorianHelmet_eldarSergeant_GH", \
"ls_mandalorianHelmet_ordoGrunt_GH", \
"ls_mandalorianHelmet_ordoSergeant_GH", \
"ls_mandalorianHelmet_saxonGrunt_GH", \
"ls_mandalorianHelmet_saxonSergeant_GH", \
"ls_mandalorianHelmet_superCommandoGrunt_GH", \
"ls_mandalorianHelmet_superCommandoSergeant_GH", \
"ls_mandalorianHelmet_superCommandoCaptain_GH", \
"ls_mandalorianHelmet_vizslaGrunt_GH", \
"ls_mandalorianHelmet_vizslaSergeant_GH", \
"ls_mandalorianHelmet_vizslaCaptain_GH", \
"ls_mandalorianHelmet_deathwatchGrunt_GH", \
"ls_mandalorianHelmet_deathwatchSergeant_GH", \
"ls_mandalorianHelmet_deathwatchCaptain_GH", \
"ls_mandalorianHelmet_deathwatchNightowl_GH"

#undef WEAPONS_LIST
#define WEAPONS_LIST \
"ls_mandalorianHelmet_armorer", \
"ls_mandalorianHelmet_dinDjarin", \
"ls_mandalorianHelmet_elite", \
"ls_mandalorianHelmet_executioner", \
"ls_mandalorianHelmet_nightowl", \
"ls_mandalorianHelmet_stalker", \
"ls_mandalorianHelmet_traditional", \
"ls_mandalorianHelmet_deathwatchGrunt", \
"ls_mandalorianHelmet_deathwatchSergeant", \
"ls_mandalorianHelmet_deathwatchCaptain", \
"ls_mandalorianHelmet_deathwatchNightowl", \
"ls_mandalorianHelmet_eldarGrunt", \
"ls_mandalorianHelmet_eldarSergeant", \
"ls_mandalorianHelmet_ordoGrunt", \
"ls_mandalorianHelmet_ordoSergeant", \
"ls_mandalorianHelmet_saxonGrunt", \
"ls_mandalorianHelmet_saxonSergeant", \
"ls_mandalorianHelmet_superCommandoGrunt", \
"ls_mandalorianHelmet_superCommandoSergeant", \
"ls_mandalorianHelmet_superCommandoCaptain", \
"ls_mandalorianHelmet_vizslaGrunt", \
"ls_mandalorianHelmet_vizslaSergeant", \
"ls_mandalorianHelmet_vizslaCaptain", \
"ls_mandalorianUniform", \
"ls_mandalorianUniform_protectorMale", \
"ls_mandalorianUniform_traditionalWoman", \
"ls_mandalorianUniform_superCommandoGrunt", \
"ls_mandalorianUniform_superCommandoSergeant", \
"ls_mandalorianVest_standard", \
"ls_mandalorianVest_protectorMale", \
"ls_mandalorianVest_traditionalPouchMale", \
"ls_mandalorianVest_traditionalPouchFemale", \
"ls_mandalorianVest_deathwatchGrunt", \
"ls_mandalorianVest_deathwatchSergeant", \
"ls_mandalorianVest_deathwatchCaptain", \
"ls_mandalorianVest_eldarGrunt", \
"ls_mandalorianVest_eldarSergeant", \
"ls_mandalorianVest_ordoGrunt", \
"ls_mandalorianVest_ordoSergeant", \
"ls_mandalorianVest_saxonGrunt", \
"ls_mandalorianVest_saxonSergeant", \
"ls_mandalorianVest_superCommandoGrunt", \
"ls_mandalorianVest_superCommandoSergeant", \
"ls_mandalorianVest_vizslaGrunt", \
"ls_mandalorianVest_vizslaSergeant", \
"ls_mandalorianVest_vizslaCaptain", \
"ls_mandalorian_rangefinder"
