class ls_CfgMovesKillerRabbit {
    collisionGeomCompPattern[] = {1, 3};
    collisionVertexPattern[] = {"1a", "2a", "3a", "4a", "5a", "6a", "7a", "8a", "9a", "10a", "11a", "12a", "13a", "14a", "15a", "16a", "17a", "18a", "19a", "20a", "21a", "22a", "23a", "24a", "25a", "26a", "27a", "28a", "29a", "30a", "31a", "32a", "33a", "34a", "1c", "2c", "3c", "4c", "5c", "6c", "7c", "8c"};
    skeletonName = "Rabbit_F";
    gestures = "";
    transitionsDisabled[] = {};
    transitionsInterpolated[] = {};
    transitionsSimple[] = {};
    class Actions {
        class NoActions {
            turnSpeed = 15;
            limitFast = 5.5;
            useFastMove = 0;
            upDegree = 0;
            stance = "ManStanceUndefined";
            // ManActions
            Stop = "";
            StopRelaxed = "";
            TurnL = "";
            TurnR = "";
            TurnLRelaxed = "";
            TurnRRelaxed = "";
            Default = "";
            JumpOff = "";
            ReloadMagazine = "";
            ReloadMGun = "";
            ReloadAT = "";
            ReloadMortar = "";
            ThrowGrenade = "";
            WalkF = "";
            WalkLF = "";
            WalkRF = "";
            WalkL = "";
            WalkR = "";
            WalkLB = "";
            WalkRB = "";
            WalkB = "";
            SlowF = "";
            SlowLF = "";
            SlowRF = "";
            SlowL = "";
            SlowR = "";
            SlowLB = "";
            SlowRB = "";
            SlowB = "";
            FastF = "";
            FastLF = "";
            FastRF = "";
            FastL = "";
            FastR = "";
            FastLB = "";
            FastRB = "";
            FastB = "";
            EvasiveForward = "";
            EvasiveLeft = "";
            EvasiveRight = "";
            EvasiveBack = "";
            StartSwim = "";
            StopSwim = "";
            Down = "";
            Up = "";
            PlayerStand = "";
            PlayerCrouch = "";
            PlayerProne = "";
            Lying = "";
            Stand = "";
            Combat = "";
            Crouch = "";
            CanNotMove = "";
            Civil = "";
            CivilLying = "";
            FireNotPossible = "";
            Die = "";
            WeaponOn = "";
            WeaponOff = "";
            StrokeFist = "";
            StrokeGun = "";
            SitDown = "";
            Salute = "";
            BinocOn = "";
            BinocOff = "";
            PutDown = "";
            PutDownEnd = "";
            Medic = "";
            Treated = "";
            LadderOnDown = "";
            LadderOnUp = "";
            LadderOff = "";
            LadderOffTop = "";
            LadderOffBottom = "";
            GetInLow = "";
            GetInMedium = "";
            GetInHigh = "";
            GetOutLow = "";
            GetOutMedium = "";
            GetOutHigh = "";
            TakeFlag = "";
            HandGunOn = "";
            LookAround = "";
            Eat = "";
            StopEat = "";
            Rest = "";
            StopRest = "";
        };
        class RabbitActions: NoActions {
            Stop = "Rabbit_Idle_Stop";
            StopRelaxed = "Rabbit_Idle_Stop";
            TurnL = "Rabbit_Idle_Stop";
            TurnR = "Rabbit_Idle_Stop";
            TurnLRelaxed = "Rabbit_Idle_Stop";
            TurnRRelaxed = "Rabbit_Idle_Stop";
            Default = "Rabbit_Idle_Stop";
            JumpOff = "Rabbit_Idle_Stop";
            WalkF = "Rabbit_Idle_Hop";
            PlayerWalkF = "Rabbit_Idle_Hop";
            PlayerWalkLF = "Rabbit_Idle_Hop";
            PlayerWalkRF = "Rabbit_Idle_Hop";
            SlowF = "Rabbit_Idle_Sprint";
            PlayerSlowF = "Rabbit_Idle_Run";
            PlayerSlowLF = "Rabbit_Idle_Run";
            PlayerSlowRF = "Rabbit_Idle_Run";
            FastF = "Rabbit_Idle_Sprint";
            PlayerTactF = "Rabbit_Idle_Sprint";
            PlayerTactLF = "Rabbit_Idle_Sprint";
            PlayerTactRF = "Rabbit_Idle_Sprint";
            PlayerTactL = "Rabbit_Idle_Sprint";
            PlayerTactR = "Rabbit_Idle_Sprint";
            PlayerTactLB = "Rabbit_Idle_Sprint";
            PlayerTactRB = "Rabbit_Idle_Sprint";
            PlayerTactB = "Rabbit_Idle_Sprint";
            LimpF = "Rabbit_Idle_Hop";
            LimpLF = "Rabbit_Idle_Hop";
            LimpRF = "Rabbit_Idle_Hop";
            LimpL = "Rabbit_Idle_Hop";
            LimpR = "Rabbit_Idle_Hop";
            LimpB = "Rabbit_Idle_Hop";
            LimpLB = "Rabbit_Idle_Hop";
            LimpRB = "Rabbit_Idle_Hop";
            EvasiveForward = "Rabbit_Idle_Sprint";
            Down = "Rabbit_Idle_Stop";
            Up = "Rabbit_Idle_Stop";
            PlayerStand = "Rabbit_Idle_Stop";
            PlayerCrouch = "Rabbit_Idle_Stop";
            PlayerProne = "Rabbit_Idle_Stop";
            Lying = "Rabbit_Idle_Stop";
            Stand = "Rabbit_Idle_Stop";
            Combat = "Rabbit_Idle_Stop";
            Crouch = "Rabbit_Idle_Stop";
            CanNotMove = "Rabbit_Idle_Stop";
            Civil = "Rabbit_Idle_Stop";
            CivilLying = "Rabbit_Idle_Stop";
            FireNotPossible = "Rabbit_Idle_Stop";
            Die = "Rabbit_Die";
            LookAround = "";
            turnSpeed = 300;
            limitFast = 5.5;
            useFastMove = 0;
            upDegree = "ManPosNoWeapon";
        };
    };
    class BlendAnims {
        aimingDefault[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingRifleSlingDefault[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingPistol[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingLauncher[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingCivil[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingCivilKneel[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingLying[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingLyingPistol[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        legsLyingAiming[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        legsLyingAimingPistol[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingUpDefault[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingUpRifleSlingDefault[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingUpCivilKneel[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingUpLying[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingUpPistol[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingUpCivil[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        aimingUpLauncher[] = {"head", 1, "leftEar", 1, "rightEar", 1};
        headDefault[] = {"head", 1, "neck1", 0.5, "neck", 0.5};
        legsDefault[] = {"LeftUpLeg", 0.9, "LeftUpLegRoll", 0.9, "LeftLeg", 0.95, "LeftLegRoll", 0.95, "LeftFoot", 1, "LeftToeBase", 1, "RightUpLeg", 0.9, "RightUpLegRoll", 0.9, "RightLeg", 0.95, "RightLegRoll", 0.95, "RightFoot", 1, "RightToeBase", 1};
        idleDefault[] = {"Pelvis", 1, "Spine", 1, "Spine1", 1, "Spine2", 1, "Spine3", 1, "Camera", 1, "weapon", 1, "launcher", 1, "neck", 1, "neck1", 1, "head", 1, "LeftShoulder", 1, "LeftArm", 1, "LeftArmRoll", 1, "LeftForeArm", 1, "LeftForeArmRoll", 1, "LeftHand", 1, "LeftHandRing", 1, "LeftHandRing1", 1, "LeftHandRing2", 1, "LeftHandRing3", 1, "LeftHandPinky1", 1, "LeftHandPinky2", 1, "LeftHandPinky3", 1, "LeftHandMiddle1", 1, "LeftHandMiddle2", 1, "LeftHandMiddle3", 1, "LeftHandIndex1", 1, "LeftHandIndex2", 1, "LeftHandIndex3", 1, "LeftHandThumb1", 1, "LeftHandThumb2", 1, "LeftHandThumb3", 1, "RightShoulder", 1, "RightArm", 1, "RightArmRoll", 1, "RightForeArm", 1, "RightForeArmRoll", 1, "RightHand", 1, "RightHandRing", 1, "RightHandRing1", 1, "RightHandRing2", 1, "RightHandRing3", 1, "RightHandPinky1", 1, "RightHandPinky2", 1, "RightHandPinky3", 1, "RightHandMiddle1", 1, "RightHandMiddle2", 1, "RightHandMiddle3", 1, "RightHandIndex1", 1, "RightHandIndex2", 1, "RightHandIndex3", 1, "RightHandThumb1", 1, "RightHandThumb2", 1, "RightHandThumb3", 1, "LeftUpLeg", 1, "LeftUpLegRoll", 1, "LeftLeg", 1, "LeftLegRoll", 1, "LeftFoot", 1, "LeftToeBase", 1, "RightUpLeg", 1, "RightUpLegRoll", 1, "RightLeg", 1, "RightLegRoll", 1, "RightFoot", 1, "RightToeBase", 1};

        class MaskStart0 {
            weight = 0.85;
        };

        weaponSwitching[] = {"head", 0.6, "neck1", 0.6, "neck", 0.6, "weapon", 1, "launcher", 1, "LeftShoulder", 1, "LeftArm", 1, "LeftArmRoll", 1, "LeftForeArm", 1, "LeftForeArmRoll", 1, "LeftHand", 1, "LeftHandRing", 1, "LeftHandPinky1", 1, "LeftHandPinky2", 1, "LeftHandPinky3", 1, "LeftHandRing1", 1, "LeftHandRing2", 1, "LeftHandRing3", 1, "LeftHandMiddle1", 1, "LeftHandMiddle2", 1, "LeftHandMiddle3", 1, "LeftHandIndex1", 1, "LeftHandIndex2", 1, "LeftHandIndex3", 1, "LeftHandThumb1", 1, "LeftHandThumb2", 1, "LeftHandThumb3", 1, "RightShoulder", 1, "RightArm", 1, "RightArmRoll", 1, "RightForeArm", 1, "RightForeArmRoll", 1, "RightHand", 1, "RightHandRing", 1, "RightHandPinky1", 1, "RightHandPinky2", 1, "RightHandPinky3", 1, "RightHandRing1", 1, "RightHandRing2", 1, "RightHandRing3", 1, "RightHandMiddle1", 1, "RightHandMiddle2", 1, "RightHandMiddle3", 1, "RightHandIndex1", 1, "RightHandIndex2", 1, "RightHandIndex3", 1, "RightHandThumb1", 1, "RightHandThumb2", 1, "RightHandThumb3", 1, "Spine", 0.3, "Spine1", 0.4, "Spine2", 0.5, "Spine3", 0.6, "pelvis", "MaskStart0"};
        crewShake_shoulders[] = {"weapon", 0.5, "Camera", 0.5, "launcher", 0.5, "Head", 0.5, "Neck", 0.5, "Neck1", 0.5, "LeftShoulder", 0.45, "LeftArm", 0.35, "LeftArmRoll", 0.25, "LeftForeArm", 0.15, "RightShoulder", 0.45, "RightArm", 0.35, "RightArmRoll", 0.25, "RightForeArm", 0.315, "spine3", 0.475, "spine2", 0.25, "LeftUpLeg", 0.1, "LeftUpLegRoll", 0.25, "LeftLeg", 0.1, "RightUpLeg", 0.1, "RightUpLegRoll", 0.25, "RightLeg", 0.1};
        aimingKneelUnarmedDefault = "";
        leaningDefault[] = {"weapon", 1, "Camera", 1, "launcher", 1, "Head", 1, "Neck", 1, "Neck1", 1, "LeftShoulder", 1, "LeftArm", 1, "LeftArmRoll", 1, "LeftForeArm", 1, "LeftForeArmRoll", 1, "LeftHand", 1, "LeftHandRing", 1, "LeftHandPinky1", 1, "LeftHandPinky2", 1, "LeftHandPinky3", 1, "LeftHandRing1", 1, "LeftHandRing2", 1, "LeftHandRing3", 1, "LeftHandMiddle1", 1, "LeftHandMiddle2", 1, "LeftHandMiddle3", 1, "LeftHandIndex1", 1, "LeftHandIndex2", 1, "LeftHandIndex3", 1, "LeftHandThumb1", 1, "LeftHandThumb2", 1, "LeftHandThumb3", 1, "RightShoulder", 1, "RightArm", 1, "RightArmRoll", 1, "RightForeArm", 1, "RightForeArmRoll", 1, "RightHand", 1, "RightHandRing", 1, "RightHandPinky1", 1, "RightHandPinky2", 1, "RightHandPinky3", 1, "RightHandRing1", 1, "RightHandRing2", 1, "RightHandRing3", 1, "RightHandMiddle1", 1, "RightHandMiddle2", 1, "RightHandMiddle3", 1, "RightHandIndex1", 1, "RightHandIndex2", 1, "RightHandIndex3", 1, "RightHandThumb1", 1, "RightHandThumb2", 1, "RightHandThumb3", 1, "spine3", 0.95, "spine2", 0.9, "spine1", 0.8, "spine", 0.7, "pelvis", 0.4};
        crewShake_half[] = {"weapon", 0.5, "Camera", 0.5, "launcher", 0.5, "Head", 0.5, "Neck", 0.5, "Neck1", 0.5, "LeftShoulder", 0.45, "LeftArm", 0.35, "LeftArmRoll", 0.25, "LeftForeArm", 0.15, "RightShoulder", 0.45, "RightArm", 0.35, "RightArmRoll", 0.25, "RightForeArm", 0.315, "spine3", 0.475, "spine2", 0.45, "spine1", 0.4, "spine", 0.35, "pelvis", 0.2, "LeftUpLeg", 0.1, "LeftUpLegRoll", 0.25, "LeftLeg", 0.1, "RightUpLeg", 0.1, "RightUpLegRoll", 0.25, "RightLeg", 0.1};
        crewShake[] = {"weapon", 1, "Camera", 1, "launcher", 1, "Head", 1, "Neck", 1, "Neck1", 1, "LeftShoulder", 0.9, "LeftArm", 0.7, "LeftArmRoll", 0.5, "LeftForeArm", 0.3, "RightShoulder", 0.9, "RightArm", 0.7, "RightArmRoll", 0.5, "RightForeArm", 0.3, "spine3", 0.95, "spine2", 0.9, "spine1", 0.8, "spine", 0.7, "pelvis", 0.4, "LeftUpLeg", 0.2, "LeftUpLegRoll", 0.5, "LeftLeg", 0.2, "RightUpLeg", 0.2, "RightUpLegRoll", 0.5, "RightLeg", 0.2};
        wholeBody[] = {"Pelvis", 1, "Spine", 1, "Spine1", 1, "Spine2", 1, "Spine3", 1, "Camera", 1, "weapon", 1, "launcher", 1, "neck", 1, "neck1", 1, "head", 1, "LeftShoulder", 1, "LeftArm", 1, "LeftArmRoll", 1, "LeftForeArm", 1, "LeftForeArmRoll", 1, "LeftHand", 1, "LeftHandRing", 1, "LeftHandRing1", 1, "LeftHandRing2", 1, "LeftHandRing3", 1, "LeftHandPinky1", 1, "LeftHandPinky2", 1, "LeftHandPinky3", 1, "LeftHandMiddle1", 1, "LeftHandMiddle2", 1, "LeftHandMiddle3", 1, "LeftHandIndex1", 1, "LeftHandIndex2", 1, "LeftHandIndex3", 1, "LeftHandThumb1", 1, "LeftHandThumb2", 1, "LeftHandThumb3", 1, "RightShoulder", 1, "RightArm", 1, "RightArmRoll", 1, "RightForeArm", 1, "RightForeArmRoll", 1, "RightHand", 1, "RightHandRing", 1, "RightHandRing1", 1, "RightHandRing2", 1, "RightHandRing3", 1, "RightHandPinky1", 1, "RightHandPinky2", 1, "RightHandPinky3", 1, "RightHandMiddle1", 1, "RightHandMiddle2", 1, "RightHandMiddle3", 1, "RightHandIndex1", 1, "RightHandIndex2", 1, "RightHandIndex3", 1, "RightHandThumb1", 1, "RightHandThumb2", 1, "RightHandThumb3", 1, "LeftUpLeg", 1, "LeftUpLegRoll", 1, "LeftLeg", 1, "LeftLegRoll", 1, "LeftFoot", 1, "LeftToeBase", 1, "RightUpLeg", 1, "RightUpLegRoll", 1, "RightLeg", 1, "RightLegRoll", 1, "RightFoot", 1, "RightToeBase", 1};
        aimingNo[] = {};
        legsNo[] = {};
        headNo[] = {};
        empty[] = {};
    };

    class Default {
        minPlayTime = 0;
        useIdles = 1;
        variantsPlayer[] = {};
        variantsAI[] = {""};
        variantAfter[] = {5, 10, 20};
        connectFrom[] = {};
        connectTo[] = {};
        interpolateWith[] = {};
        interpolateTo[] = {};
        interpolateFrom[] = {};
        leftHandIKCurve[] = {};
        rightHandIKCurve[] = {};
        stamina = 1;
        weaponLowered = 0;
        weaponObstructed = 0;
        canBlendStep = 0;
        idle = "idleDefault";
        access = 3;
        actions = "NoActions";
        file = "";
        looped = 1;
        speed = 0.5;
        enableOptics = 0;
        disableWeaponsLong = 0;
        enableMissile = 0;
        enableBinocular = 0;
        showItemInHand = 0;
        showItemInRightHand = 0;
        showHandGun = 0;
        onLandBeg = 0;
        onLandEnd = 0;
        onLadder = 0;
        canReload = 1;
        duty = -0.5;
        visibleSize = 0.6;
        aimPrecision = 1;
        static = 0;
        relSpeedMin = 1;
        relSpeedMax = 1;
        soundEnabled = 1;
        soundOverride = "";
        terminal = 0;
        ragdoll = 0;
        limitGunMovement = 1;
        equivalentTo = "";
        connectAs = "";
        ignoreMinPlayTime[] = {"Unconscious"};
        leaning = "leaningDefault";
        leaningFactorBeg = 0;
        leaningFactorEnd = 0;
        leaningFactorZeroPoint = -1;
        interpolationSpeed = 6;
        collisionShape = "\a3\animals_f\Rabbit\Rabbit_CollShape.p3d";
        hasCollShapeSafe = 0;
        collisionShapeSafe = "";
        enableAutoActions = 0;
        leftHandIKEnd = 0;
        leftHandIKBeg = 0;
        rightHandIKBeg = 0;
        rightHandIKEnd = 0;
        weaponIK = 0;
        preload = 0;
        Walkcycles = 1;
        forceAim = 0;
        adjstance = "m";
        camShakeFire = 0;
    };

    class DefaultDie: Default {
        aiming = "aimingNo";
        aimingBody = "aimingNo";
        legs = "legsNo";
        head = "headNo";
        disableWeapons = 1;
        interpolationRestart = 1;
        soundEdge[] = {0.45};
        boundingSphere = 1.5;
        enableDirectControl = 0;
        showWeaponAim = 0;
        canPullTrigger = 0;
        headBobMode = 1;
        headBobStrength = -1;
    };

    class StandBase {
        disableWeapons = 1;
        leaningFactorBeg = 1;
        leaningFactorEnd = 1;
        headBobMode = 2;
        headBobStrength = 0.20398;
    };

    class States {

        class Rabbit_Idle_Stop: StandBase {
            actions = "RabbitActions";
            file = "\A3\Animals_F\Rabbit\data\Anim\rabbit_basicIdle";
            connectTo[] = {"Rabbit_Idle_Stop", 0.02, "Rabbit_Idle_StopV1", 0.02};
            interpolateTo[] = {"Rabbit_Idle_Hop", 0.1, "Rabbit_Stop", 0.5, "Rabbit_Hop", 0.5, "Rabbit_Die", 0.1};
            duty = 1;
            static = 1;
            relSpeedMin = 0.5;
            relSpeedMax = 1.1;
            soundEnabled = 0;
            enableBinocular = 1;
            leftHandIKBeg = 1;
            leftHandIKCurve[] = {1};
            leftHandIKEnd = 1;
            rightHandIKBeg = 1;
            rightHandIKCurve[] = {1};
            rightHandIKEnd = 1;
            weaponIK = 1;
            canPullTrigger = 0;
            interpolationSpeed = 5;
            canBlendStep = 1;
            headBobStrength = 0.054726;
            weaponLowered = 1;
        };

        class Rabbit_Idle_StopV1: Rabbit_Idle_Stop {
            file = "\A3\Animals_F\Rabbit\data\Anim\rabbit_idleLookAround";
            speed = -6;
        };

        class Rabbit_Idle_Hop: StandBase {
            actions = "RabbitActions";
            file = "\A3\Animals_F\Rabbit\data\Anim\rabbit_basicIdle";
            duty = -0.4;
            variantsAI[] = {"Rabbit_Idle_Stop", 0.3, "Rabbit_Idle_StopV1", 0.3, "Rabbit_Idle_Hop", 0.4};
            // speed = -0.5; // These properties were defined twice, not sure which one is correct
            // relSpeedMin = 1;
            // relSpeedMax = 1;
            connectTo[] = {"Rabbit_Idle_Stop", 0.02, "Rabbit_Idle_StopV1", 0.02};
            interpolateTo[] = {"Rabbit_Idle_Hop", 0.1, "Rabbit_Stop", 0.5, "Rabbit_Hop", 0.5, "Rabbit_Die", 0.1};
            preload = 1;
            showWeaponAim = 0;
            disableWeapons = 0;
            disableWeaponsLong = 1;
            speed = 1e+010;
            static = 1;
            relSpeedMin = 0.5;
            relSpeedMax = 1.1;
            soundEnabled = 0;
            enableBinocular = 1;
            leftHandIKBeg = 1;
            leftHandIKCurve[] = {1};
            leftHandIKEnd = 1;
            rightHandIKBeg = 1;
            rightHandIKCurve[] = {1};
            rightHandIKEnd = 1;
            weaponIK = 1;
            canPullTrigger = 0;
            interpolationSpeed = 5;
            canBlendStep = 1;
            headBobStrength = 0.054726;
            weaponLowered = 1;
        };

        class Rabbit_Idle_Run: Rabbit_Idle_Hop {
            file = "\A3\Animals_F\Rabbit\data\Anim\rabbit_run";
            duty = -0.5;
            relSpeedMin = 0.5;
            relSpeedMax = 1;
            speed = -0.2;
            connectFrom[] = {"Rabbit_Idle_Sprint", 0.2, "Rabbit_Idle_Hop", 0.1};
            connectTo[] = {"Rabbit_Idle_Sprint", 0.2, "Rabbit_Idle_Hop", 0.1};
            interpolateTo[] = {"Rabbit_Die", 0.1};
        };

        class Rabbit_Idle_Sprint: Rabbit_Idle_Run {
            file = "\A3\Animals_F\Rabbit\data\Anim\rabbit_run";
            duty = 0.5;
            relSpeedMin = 0.5;
            relSpeedMax = 1;
            speed = 1;
            connectTo[] = {"Rabbit_Idle_Sprint", 0.1, "Rabbit_Idle_Run", 0.2};
            interpolateTo[] = {"Rabbit_Die", 0.1};
        };

        class Rabbit_Die: DefaultDie {
            actions = "NoActions";
            file = "\A3\Animals_F\Rabbit\data\Anim\rabbit_death";
            speed = 1.4;
            looped = 0;
            variantsPlayer[] = {};
            variantsAI[] = {"Rabbit_Die", 0.5, "Rabbit_Die3", 0.5};
            variantAfter[] = {0, 0, 0};
            terminal = 1;
        };

        class Rabbit_Die3: Rabbit_Die {
            file = "\A3\Animals_F\Rabbit\data\Anim\rabbit_death3";
        };

        class Rabbit_Stop: Rabbit_Idle_Stop {
            connectTo[] = {"Rabbit_Stop", 0.02};
            interpolateTo[] = {"Rabbit_Idle_Stop", 0.02, "Rabbit_Hop", 0.02, "Rabbit_Die", 0.02};
        };

        class Rabbit_Hop: Rabbit_Idle_Hop {
            connectTo[] = {"Rabbit_Stop", 0.02};
            interpolateTo[] = {"Rabbit_Idle_Stop", 0.02, "Rabbit_Hop", 0.02, "Rabbit_Die", 0.02};
        };
    };
};
