LEGACY_COMMANDO_HELMET(aiwhaDikut,Aiwha [Di'kut]);
LEGACY_COMMANDO_HELMET(aiwhaSarge,Aiwha [Sarge]);
LEGACY_COMMANDO_HELMET(aiwhaTyto,Aiwha [Tyto]);
LEGACY_COMMANDO_HELMET(aiwhaZag,Aiwha [Zag]);
LEGACY_COMMANDO_HELMET(bravoRam,Bravo [Ram]);
LEGACY_COMMANDO_HELMET(bravo2,Bravo [2]);
LEGACY_COMMANDO_HELMET(bravo3,Bravo [3]);
LEGACY_COMMANDO_HELMET(bravo4,Bravo [4]);
LEGACY_COMMANDO_HELMET(deltaBoss,Delta [Boss]);
LEGACY_COMMANDO_HELMET(deltaFixer,Delta [Fixer]);
LEGACY_COMMANDO_HELMET(deltaScorch,Delta [Scorch]);
LEGACY_COMMANDO_HELMET(deltaSev,Delta [Sev]);
LEGACY_COMMANDO_HELMET(foxtrotGregor,Foxtrot [Gregor]);
LEGACY_COMMANDO_HELMET(hodasalJungle,Hodasal Camo);
LEGACY_COMMANDO_HELMET(mpGunner,Gunner);
LEGACY_COMMANDO_HELMET(mpMarksman,Marksman);
LEGACY_COMMANDO_HELMET(mpRecon,Recon);
LEGACY_COMMANDO_HELMET(mpStealth,Stealth);
LEGACY_COMMANDO_HELMET(omega,Omega);
LEGACY_COMMANDO_HELMET(yayaxCov,Yayax [Cov]);
LEGACY_COMMANDO_HELMET(yayaxDev,Yayax [Dev]);
LEGACY_COMMANDO_HELMET(yayaxJind,Yayax [Jind]);
LEGACY_COMMANDO_HELMET(yayaxYover,Yayax [Yover]);
