COMMANDO_HELMET(aiwhaDikut,Aiwha [Di'kut]);
COMMANDO_HELMET(aiwhaSarge,Aiwha [Sarge]);
COMMANDO_HELMET(aiwhaTyto,Aiwha [Tyto]);
COMMANDO_HELMET(aiwhaZag,Aiwha [Zag]);
COMMANDO_HELMET(bravoRam,Bravo [Ram]);
COMMANDO_HELMET(bravo2,Bravo [2]);
COMMANDO_HELMET(bravo3,Bravo [3]);
COMMANDO_HELMET(bravo4,Bravo [4]);
COMMANDO_HELMET(deltaBoss,Delta [Boss]);
COMMANDO_HELMET(deltaFixer,Delta [Fixer]);
COMMANDO_HELMET(deltaScorch,Delta [Scorch]);
COMMANDO_HELMET(deltaSev,Delta [Sev]);
COMMANDO_HELMET(foxtrotGregor,Foxtrot [Gregor]);
COMMANDO_HELMET(hodasalJungle,Hodasal Camo);
COMMANDO_HELMET(mpGunner,Gunner);
COMMANDO_HELMET(mpMarksman,Marksman);
COMMANDO_HELMET(mpRecon,Recon);
COMMANDO_HELMET(mpStealth,Stealth);
COMMANDO_HELMET(omega,Omega);
COMMANDO_HELMET(yayaxCov,Yayax [Cov]);
COMMANDO_HELMET(yayaxDev,Yayax [Dev]);
COMMANDO_HELMET(yayaxJind,Yayax [Jind]);
COMMANDO_HELMET(yayaxYover,Yayax [Yover]);
