#define HATCH_ANIM_LENGTH 1.75

#define PATROL_RADIUS 200
#define PATROL_WAYPOINTS 3 + random 3
#define PATROL(GROUP,DISPENSER) [GROUP, DISPENSER, PATROL_RADIUS, PATROL_WAYPOINTS, "MOVE", "AWARE"] call CBA_fnc_taskPatrol
