#define IDC_TREE 710000
#define IDC_DISPENSER_GROUP_CUSTOM 710001

#define TREE_VIEW_HEIGHT 10
#define TREE_VIEW_SEARCH_HEIGHT (TREE_VIEW_HEIGHT - 2)

#define DISPENSER_GROUP_DEFAULT [[0, 0, 0], "[]"]
